### ISSUE TITLE
Domain VPN Routing v2.1.2-beta1 - update error

### ISSUE THREAD

**Issue by dorner365** [Ranger802004/asusmerlin#10]
Hi,

Congrats on the `amtm` integration.

v.2.1.1 works really well. However, the update to the current beta fails:

/jffs/scripts/domain_vpn_routing.sh update
***Dev Mode is Enabled***
domain_vpn_routing is out of date - Current Version: v2.1.1 Available Version: v2.1.2-beta1
Do you want to update to the latest beta version? v2.1.2-beta1 ***Enter Y for Yes or N for No***
> y
domain_vpn_routing: Update - domain_vpn_routing has been updated to version: v2.1.2-beta1
/jffs/scripts/domain_vpn_routing.sh: line 3857: syntax error: unexpected "}"

...and cannot start the script anymore - just hangs.

A reboot added the 'wgclient-start' script (to /jffs/scripts) containing several `cron` and `querypolicy all` entries.

Still cannot start the script...

**Comment by Ranger802004** [comment]
Let me see what is going on, can you collect debug logs?

**Comment by dorner365** [comment]
Let me know what you need; I'll do it tomorrow.
In the mean time, maybe just fixing the syntax error will get it going - I haven't tried that. I just pasted back v.2.1.1.

**Comment by Ranger802004** [comment]
Turn on debug logging in your router system log settings and then run the script and collect logs, the syntax bug is something that sometimes happens during update but it's not a true syntax bug.  I reviewed the code changes and don't see an extra }, I've seen that happen before when the code is updating.  I have 3 test routers (GT-AX11000, RT-AX86U, GT-AC2900) running the current beta and I'm not experiencing the issue so I will need to see the debug logs.

**Comment by dorner365** [comment]
On the WireGuard client page the DNS entry is optional. I did not have a DNS in there. Once I added it to each client the update proceeded correctly. Also, the `wgclient-start` file looks alright (3 lines as expected).

Closing it. Thank you for following-up so promptly.

**Comment by Ranger802004** [comment]
Updated beta has been published that addresses this issue as well as some other things.
