### ISSUE TITLE
Domain VPN Routing v2.1.2-beta3 - Query Policy - ***Error***

### ISSUE THREAD

**Issue by dorner365** [Ranger802004/asusmerlin#11]
Hi,

One of the ipsets that's working alright and gathered a few hundred IPs over the past week started showing the following error: 

Select the Policy You Want to Query: <ipset>
Query Policy: <ipset>
***New IP Addresses detected for <ipset>***
Updating Policy: <ipset>
Updated Policy: <ipset>
ipset v7.6: Null-valued element, cannot be stored in a hash type of set
domain_vpn_routing: Query Policy - ***Error*** Failed to add 0.0.0.0 to IPSET: DomainVPNRouting-<ipset>-ipv4

Press Enter to continue...

All the domains in the policy's ipset list resolve to proper IP addresses. As I said, it all works fine.

**Comment by Ranger802004** [comment]
That's interesting, your router must have failed to query a domain and returned that as the value.  You can use the deleteip function to remove it from a policy.

**Comment by dorner365** [comment]
Yes, indeed, that's one option - to manually use `deleteip` to remove it.

The other one would be to programmatically disallow that address.

**Comment by Ranger802004** [comment]
Yes, obviously I'm going to consider that but right now I'm giving you a workaround solution to resolve your immediate issue.

**Comment by dorner365** [comment]
Fair enough.

Thank you.
