### ISSUE TITLE
Wan-Failover feature request - 3rd test target

### ISSUE THREAD

**Issue by roberthawdon** [Ranger802004/asusmerlin#12]
Hi, I'm wondering if it would be possible to add a 3rd test target as sometimes if the test target itself stops responding to pings, the failover is triggered?

Google has publicly stated that their DNS endpoints priorities DNS requests over ICMP traffic and will drop pings at heavy load times. ( https://developers.google.com/speed/public-dns/docs/troubleshooting#speed )

> Google does not block ICMP or random UDP to Google Public DNS IP addresses, but there are rate limits on ICMP error replies, and ICMP traffic may be de-prioritized within Google networks.

I believe having a 3rd address to test that both interfaces can use as a fall back will result in less unnecessary failovers.

**Comment by Ranger802004** [comment]
The WAN IP Targets for each interface is customizable in the configuration menu, if 8.8.8.8 is just the default target IP so if it isn'e suitable you can change it to something that is optimal for you.  At this time a 3rd target IP would be unnecessary and may cause more complications than necessary trying to implement.  If you have issues after customizing your target IPs please reach back out.
