### ISSUE TITLE
Request: Flush Conntrack after switching WAN

### ISSUE THREAD

**Issue by RandomUserName22** [Ranger802004/asusmerlin#13]
Consider adding a conntrack -F command after switching WANs.

**Comment by Ranger802004** [comment]
This has been added into the latest beta (v2.1.1-beta3) as a configuration option (Option 30).  Please test and provide feedback, thank you.

**Comment by RandomUserName22** [comment]
Enabled.  I will let/force a few events under different scenarios occur, and let you know if it helps.

**Comment by Ranger802004** [comment]
Checking back with you on this, any updates?

**Comment by RandomUserName22** [comment]
Seems to be working great.  No adverse effects, and the transition from eth5 to eth0 and back again is clean.  The lazy devices detect connectivity, and don't bark about "no network connection".  I'd say this is a good feature and I hope it helps others.

**Comment by Ranger802004** [comment]
Excellent news, I'll go ahead and mark this one as complete and it will be included in the prod version when released.
