### ISSUE TITLE
Unable to add rules for domains - Domain VPN Routing

### ISSUE THREAD

**Issue by smarthome-enthusiast** [Ranger802004/asusmerlin#14]
Each time I query the domains to add domain routes to wgc1, I am getting this error:

Query Policy - ***Error*** Failed to add IP Rule for ************ table wgc1 priority 6000
"ip rule show" does not take any arguments.

RT-AX88U
Asus Merlin 3004.388.6
Version: v2.1.2

Is there something I'm missing?

**Comment by smarthome-enthusiast** [comment]
Managed to fix this. For those that may come here looking for the solution:

wireguard-tools/wg-quick or some other package might have installed "ip-full" from repo. It’s older than what you get with the firmware now so you can force uninstall/remove it using:

opkg remove --force-depends ip-full

**Comment by Ranger802004** [comment]
I can actually resolve this issue with an update where even with the the ip-full package installed from Entware it will use the firmware installed one.  This is something I have addressed in WAN Failover in the past.  I will reopen this case to track implementation.

**Comment by Ranger802004** [comment]
This has been added to the latest beta (v2.1.3-beta2), if you'd like to reinstall the Entware binary again and test, feel free to do so.

**Comment by smarthome-enthusiast** [comment]
Thanks, just saw the update and it works for me.
