### ISSUE TITLE
VERBOSELOGGING: parameter not set - error ver 2.1.3 beta

### ISSUE THREAD

**Issue by dorner365** [Ranger802004/asusmerlin#15]
Hi,

I have 7 policies configured and working well under ver 2.1.2.
After the beta update on ver 2.1.3, for options 8 and 9 I get the following error on 3 out of 7 policies:

"Select the Policy You Want to Restore: ssp
Restore Policy: ssp
/jffs/scripts/domain_vpn_routing.sh: line 26: VERBOSELOGGING: parameter not set" 

Note: the file domain_vpn_routing.conf shows 'VERBOSELOGGING=0' for all the policies. Changing the logging setting does not make any difference. There is no related error in the syslog.

Any suggestion?

**Comment by Ranger802004** [comment]
> Hi,
> 
> I have 7 policies configured and working well under ver 2.1.2. After the beta update on ver 2.1.3, for options 8 and 9 I get the following error on 3 out of 7 policies:
> 
> "Select the Policy You Want to Restore: ssp Restore Policy: ssp /jffs/scripts/domain_vpn_routing.sh: line 26: VERBOSELOGGING: parameter not set"
> 
> Note: the file domain_vpn_routing.conf shows 'VERBOSELOGGING=0' for all the policies. Changing the logging setting does not make any difference. There is no related error in the syslog.
> 
> Any suggestion?

Is the syntax properly formatted in the config file? It is strange it would only do this for some of the policies as that function is a loop that will just run through all of the policies using their configuration.

**Comment by dorner365** [comment]
The syntax is properly formatted. All 3 policies are well over 1000 entries each. 
Anyway, after a WAN restart things seem to be back in order. It may have been a timing issue or anything else that keeps the earth spinning. 
The error message was misleading.

Closing - thank you for looking into it.

**Comment by dorner365** [comment]
Well, shortly after I closed the issue the error reoccurred.
I reverted back to 2.1.2 and that works well as it did since October timeframe.

Here are some of my observations after the error reoccurred:
- the error log shows the script running through all the policies, but not all the rules and routes are being built for all of them (without showing an error in the log.)
- when manually running option 8 or 9 the error as described above occurs and the script quits; however, the policy rules and routes are being built and the routing policy is afterwards functional.
- a wan reset would result in the same scenario: only the same subset of policies are being built
- the remaining policies are not added overtime - only the subset of policies built initially by the script are showing. and functional.

**Comment by Ranger802004** [comment]
Can you send me a copy of your policy config file please.

**Comment by dorner365** [comment]
Hi,
Here it is...

Thank you
    On Friday, February 9, 2024 at 01:50:39 p.m. EST, Ranger802004 ***@***.***> wrote:  
 
 


Can you send me a copy of your policy config file please.

**Comment by Ranger802004** [comment]
> Hi, Here it is... I did not modify the file with a text editor. Thank you On Friday, February 9, 2024 at 01:50:39 p.m. EST, Ranger802004 ***@***.***> wrote: Can you send me a copy of your policy config file please. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

I don't see the file.  You probably need to use the GitHub site to upload it to the thread.

**Comment by Ranger802004** [comment]
Actually disregard, I think I see the issue.

**Comment by Ranger802004** [comment]
v2.1.3-beta3 has been published to the beta update channel, test this and see if it resolves your issues.

**Comment by dorner365** [comment]
Yes, it resolves the issue.

Thank you.
