### ISSUE TITLE
Update policy rules list with number options

### ISSUE THREAD

**Issue by blixten85** [Ranger802004/asusmerlin#16]
Can you add number to this script when you update the policy rules?
It's annoying to have to type the policy name every time a change is made.
An option would be to process all the policys at once. But a number would definitely be very handy.

**Comment by Ranger802004** [comment]
v2.1.3-beta3 has been published that includes this logic, test and provide feedback.  Thank you.

**Comment by blixten85** [comment]
How do i upgrade to the beta?

**Comment by Ranger802004** [comment]
Enable Dev Mode in the configuration and it will use the beta channel updates.

**Comment by blixten85** [comment]
Ah ok, nice. It seems to be working fine.  While you are at it you can add the "All" feature too as an option. :)

**Comment by Ranger802004** [comment]
I will look into that and see what I can do.

**Comment by Ranger802004** [comment]
I added this in my developer build and will include it in the next release which hopefully will be a prod release.

**Comment by blixten85** [comment]
Excellent!
