### ISSUE TITLE
Checksum blues while upgrading from DVPNR 2.1.3 Beta 3 to 2.1.3

### ISSUE THREAD

**Issue by dorner365** [Ranger802004/asusmerlin#17]
Hi,

Here's the outcome of an update attempt: 
"Make a selection:
6
domain_vpn_routing: ***domain_vpn_routing failed Checksum Check*** Current Checksum: 286a711bd6ec228528ef4979ec710ed31c874e537a48e55694aced067d3f2fab  Valid Checksum: 0347c5965c7e925b0f6eae8a694d55e5c0e6ef70bf505e2f51cf064a4e38eb0d
***Checksum Failed***
Current Checksum: 286a711bd6ec228528ef4979ec710ed31c874e537a48e55694aced067d3f2fab  Valid Checksum: 0347c5965c7e925b0f6eae8a694d55e5c0e6ef70bf505e2f51cf064a4e38eb0d
domain_vpn_routing is up to date. Do you want to reinstall domain_vpn_routing Version: v2.1.3-beta3? ***Enter Y for Yes or N for No***
>"

**Comment by Ranger802004** [comment]
That is expected behavior coming from a beta, restart the menu after doing the update and it should be updated.

**Comment by dorner365** [comment]
Well, when I tried that (way back when) it did not perform the upgrade. It was a loop - you try the upgrade, it comes up with the checksum error, then you restart the interface, the same error etc.

In any case I just upgraded from the link provided and that settled the issue.

Thank you!
