### ISSUE TITLE
Feature request for Domain VPN Routing - source IP

### ISSUE THREAD

**Issue by lexiismadd** [Ranger802004/asusmerlin#18]
Love the domain VPN routing script for Merlin!  Its solved so many of my problems! :)
Can I just ask for one possible feature to be added?
The ability to specify a source IP address or addresses for the routing policy.
So for example, you can have a policy that applies the VPN routing only when the request is coming from a specific IP address or IP addresses on the LAN..

Thanks!

**Comment by Ranger802004** [comment]
I will evaluate this for feasibility and see what we can do, I can't guarantee this will be implemented but will respond after some time looking into it.

**Comment by lexiismadd** [comment]
Thank you, hopefully it's relatively easy to implement

**Comment by Ranger802004** [comment]
This is still in consideration but I'm going to go ahead and close the issue.
