### ISSUE TITLE
Incorrect service status

### ISSUE THREAD

**Issue by gaoo90** [Ranger802004/asusmerlin#19]
Good afternoon !
Very often the switch back to the main provider does not occur.
Started after updating to 3004.388.6_2

I reinstalled the plugin, but it didn't help.

![image](https://github.com/Ranger802004/asusmerlin/assets/114869482/58080fa1-99f5-49d3-a3ff-770f7a3f93ca)
![image](https://github.com/Ranger802004/asusmerlin/assets/114869482/2de477ae-4338-4b4e-9054-958a39b04b18)
![image](https://github.com/Ranger802004/asusmerlin/assets/114869482/e17e4d85-deff-45e8-950a-2239ed61b7e8)
![image](https://github.com/Ranger802004/asusmerlin/assets/114869482/941e8170-116a-4b16-a5ac-5d1ac3e8a769)
![image](https://github.com/Ranger802004/asusmerlin/assets/114869482/42a2ebd5-4279-42c6-9920-e2739f0a7eed)

**Comment by Ranger802004** [comment]
Try enabling **NVRAM Checks (Option 14)** in the Configuration menu and restart WAN Failover.  It appears something is halting the script and that is a high probability, from the status menu it is saying unresponsive because the backend processes monitoring the WANs stopped updating 2 days prior to the screenshot.  Try this recommendation and let it run for a few days and report back, thank you.

**Comment by gaoo90** [comment]
> Try enabling **NVRAM Checks (Option 14)** in the Configuration menu and restart WAN Failover. It appears something is halting the script and that is a high probability, from the status menu it is saying unresponsive because the backend processes monitoring the WANs stopped updating 2 days prior to the screenshot. Try this recommendation and let it run for a few days and report back, thank you.

Thank you.
Your advice helped and the switch is happening correctly at the moment.

I'll watch. A few more days and I'll report the result.

**Comment by Ranger802004** [comment]
I will keep an eye out for your feedback.

**Comment by gaoo90** [comment]
At the moment your solution works fine.
No problems yet.
