### ISSUE TITLE
It won't failback!

### ISSUE THREAD

**Issue by szymond** [Ranger802004/asusmerlin#22]
I'd like to let you know, the failback mechanism fails. 

My setup is:
```
Model: RT-AX56U
Firmware Version: 388.2
JFFS Scripts: Enabled
Dual WAN: Enabled
Mode: Failover Mode
WAN Failover Version: v2.1.1
```

I had WAN0 disconnected, router properly switched to WAN1. Even though after some time WAN0 became connected, it didn't switch back to primary. I think at that time WAN Failover had "Status: Unresponsive" (but now that I restarted, I see it remains that way).

I am aware with such vague information, you won't be able to give any advice. In that case, please let me know what information (and how) should I gather next time problem occurs.

**Comment by Ranger802004** [comment]
I would need some debug logs collected as well as try turning on NVRAM Checks in the configuration menu and restart WAN Failover.

**Comment by szymond** [comment]
Thanks for providing advice. I manged to enable NVRAM checks but unfortunately I don't know how to set log level to debug. Also I tried providing path to logfile but nothing gets written there (while at the same time choosing "monitor" option prints some things on screen). 

By the way, recently similar problem with ISP happened. While modem tried to reconnect, I wanted to check what happens in wan-failover. Running wan-failover.sh only showed menu, choosing options like status/monitor/config didn't do anything. It seems to me, disconnecting ethernet cable (from modem to router) made software work again.

Anyway, it would be nice to be able to configure software to log proper information. If the same problem happens again, I'd be happy to provide logs. Also it would be nice to be able to configure  wan-failover so it sends email with logs. (By the way, there's no easily available information how email notifying works and how to configure it. Looking at the logs I deducted it uses aiprotection notification settings. I have not tried configuring it (I don't think providing my email credentials should be required to notify me nor it will work with 2fa)).

**Comment by Ranger802004** [comment]
1. Don't configure a custom syslog path unless you have one configured with another tool that your router is using for syslog.  All the setting does is override where it looks to read the syslog.  
2. You enable debug logging on the router itself on the System Log page.
3. Once you have enabled debug logging you can use the capture argument to create a log file that captures all of the logs for WAN Failover in a temporary file under /tmp and send me that file.
