### ISSUE TITLE
/jffs/scripts/domain_vpn_routing.sh showpolicy not found

### ISSUE THREAD

**Issue by hossihub** [Ranger802004/asusmerlin#23]
added a new routing policy, but in last step to verify using the showpolicy it does not show the added domain. Are there any visuals in merlin GUI for the routing tables?

**Comment by Ranger802004** [comment]
There are no visuals in the GUI.  Can you show me what you have the in the /jffs/configs/domain_vpn_routing/ folder as well as the contents of the files?

**Comment by Ranger802004** [comment]
Closing issue due to no response.
