### ISSUE TITLE
Failover or Load Balance mode for this script?

### ISSUE THREAD

**Issue by agentzh** [Ranger802004/asusmerlin#25]
Hi @Ranger802004 first of all, thanks a lot of the script!

I have some confusions regarding the instruction "ASUS Factory Failover Disabled" in `wan-failover-readme.txt`. Does that mean I need to use the load balance mode for the Dual WAN in the merlin web UI? Or does it mean I should enable Failover but leave the Failback checkbox unchecked?

I tried the Failover mode without failback, but the main WAN has no port forwarding while the secondary one does. Is it because I should use the load balance mode instead?

If I use the load balance mode, will the failover script automatically turn off the problematic WAN for me?

Many thanks!

**Comment by agentzh** [comment]
OK, the load balance mode also has problems, it leads to intermittent network errors like "Network unreachable" on the client devices. BTW, I'm using the RT-AX88U router.

**Comment by agentzh** [comment]
And I'm using wan-failover.sh v2.1.1 and Merlin firmware 3004.388.7

**Comment by ysmolski** [comment]
In GUI you should set load balance like so:
![Screenshot 2024-07-20 at 12 35 43](https://github.com/user-attachments/assets/6abdddd4-928f-42c6-b931-b8b6e51e5f26)
Then you install the script and it does some tunings on its own.

As for case when things are not working, you want to check logs, specifically enable debug logging in the system log settings (Log only messages more urgent than -> Debug) and then capture it via WF menu in atmt. You could post logs here if you are not seeing how to fix the problem.

**Comment by Ranger802004** [comment]
"ASUS Factory Failover Disabled" refers to the default failover options configured in the GUI and not what mode the router is in.  As far as network unreachable, you'd have to do more network diagnostics to see what is causing the issue, what kind of clients are having these issues? As far as the router goes it's tagging sessions to stick to a specific WAN interface so if the client is not retaining the session properly it can "break" that functionality.  Yes that is correct, you want to leave the GUI Network Monitoring options unchecked.
