### ISSUE TITLE
wan-failover: add an option to probe dns as a target for WAN

### ISSUE THREAD

**Issue by ysmolski** [Ranger802004/asusmerlin#26]
Good addon I must say. It makes fail over react very quickly when some WAN goes down. But I have a feature request to make it even more smooth experience.

Right now only pings on static targets can be used for probing the health of WAN interface. 

My provider has this weird issue of DNS servers going down often. Pings to 8.8.8.8 works, but provider's DNS is totally down. This leads to sitation when clients are not able to use internet because it never fails over.

1st possible solution: Use DNS for probing as more reliable, because public DNS servers prioritize DNS traffic over ICMP.

2nd: As a temporary workaround I have set target IP for each WAN as the IP addresses for DNS returned by provider's DHCPs. Evolving this idea, would it be possible to use DNS servers returned by providers as targets for ping probes? It could be an option in the script to use DNS server as targets automatically instead of manual assigment.

**Comment by ysmolski** [comment]
Updated the ticket with more ideas. Thanks again for all the work that you put into this script, @Ranger802004! Outstanding script!

**Comment by Ranger802004** [comment]
This is something I have considered adding but would require a major overhaul to incorporate but it's still in consideration for future releases.
