### ISSUE TITLE
Installation and uninstallation seem to hang on GT-BE98 Pro

### ISSUE THREAD

**Issue by p1r473** [Ranger802004/asusmerlin#27]
Hi, 
Installation and uninstallation seem to hang on GT-BE98 Pro

On uninstall it hangs after deleting the script 
On install it hangs at getting systems settings

**Comment by Ranger802004** [comment]
Unfortunately support for the newer devices running on 3006.x firmware have not been tested or developed for that firmware.  Are you trying to use WAN Failover or Domain VPN Routing? Do you have any logs you can provide for me? I believe some stuff changes in that firmware that doesn't map to the same paths as 3004.x so some changes would have to be made to support both.
