### ISSUE TITLE
[Feature Request] Wildcard support or parse adguardhome log

### ISSUE THREAD

**Issue by romanlex** [Ranger802004/asusmerlin#28]
In this thread https://www.snbforums.com/threads/domain-based-vpn-routing-script.79264/page-25 you discussed the possibility of parsing logs of AdguardHome
I want to add a domain with other subdomains, for example googlevideo.com and *.googlevideo.com
Now I add domains separately :(
```
rr1---sn-4g5ednds.googlevideo.com
rr1---sn-8ph2xajvh-31oe.googlevideo.com
rr13---sn-n8v7kn7y.googlevideo.com
rr13---sn-n8v7zns7.googlevideo.com
rr18---sn-n8v7sney.googlevideo.com
rr2---sn-8ph2xajvh-31oe.googlevideo.com
rr3---sn-4g5lznez.googlevideo.com
rr4---sn-4g5lzney.googlevideo.com
rr4---sn-n8v7znzl.googlevideo.com
rr5---sn-4g5ednkl.googlevideo.com
rr5---sn-4g5lznlz.googlevideo.com
rr7---sn-n8v7znz7.googlevideo.com
rr9---sn-n8v7znsl.googlevideo.com
```
May be we can add to domain list `*.googlevideo.com` and search all dns request and collect ips for this domains

**Comment by Gundabadec** [comment]
Or add ability to add range of ip 188.114.0.0/16, 172.64.0.0/16, 104.18.0.0/16

**Comment by Ranger802004** [comment]
> In this thread https://www.snbforums.com/threads/domain-based-vpn-routing-script.79264/page-25 you discussed the possibility of parsing logs of AdguardHome I want to add a domain with other subdomains, for example googlevideo.com and *.googlevideo.com Now I add domains separately :(
> 
> ```
> rr1---sn-4g5ednds.googlevideo.com
> rr1---sn-8ph2xajvh-31oe.googlevideo.com
> rr13---sn-n8v7kn7y.googlevideo.com
> rr13---sn-n8v7zns7.googlevideo.com
> rr18---sn-n8v7sney.googlevideo.com
> rr2---sn-8ph2xajvh-31oe.googlevideo.com
> rr3---sn-4g5lznez.googlevideo.com
> rr4---sn-4g5lzney.googlevideo.com
> rr4---sn-n8v7znzl.googlevideo.com
> rr5---sn-4g5ednkl.googlevideo.com
> rr5---sn-4g5lznlz.googlevideo.com
> rr7---sn-n8v7znz7.googlevideo.com
> rr9---sn-n8v7znsl.googlevideo.com
> ```
> 
> May be we can add to domain list `*.googlevideo.com` and search all dns request and collect ips for this domains

Is there a separate dns log AdGuardHome uses or are you getting those logs from the path specified in your dnsmasq config?

**Comment by Ranger802004** [comment]
> Or add ability to add range of ip like: 188.114.0.0/16, 172.64.0.0/16, 104.18.0.0/16

This a core feature of VPN Director policy rules, that functionality in Domain VPN Routing would be redundant capabilities of what you already have with ASUS Merlin firmware installed.

**Comment by romanlex** [comment]
> Is there a separate dns log AdGuardHome uses or are you getting those logs from the path specified in your dnsmasq config?

In adguard home I can enable querylog 
![image](https://github.com/user-attachments/assets/8db7b5bc-a11d-4536-bc35-870f823d56f3)

https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#rdns-clients

**Comment by Ranger802004** [comment]
I am actively looking into implementing this now.

**Comment by romanlex** [comment]
may be we can use https://github.com/AnyMoe/ipset-dns ?

**Comment by Ranger802004** [comment]
I already query the DNS log if it's enabled but it doesn't do wildcard match currently which is something I'll be trying to implement soon, no guarantees but I'm working on it.

**Comment by computersteve** [comment]
How is this feature going !! It would greatly help me. I notice that streaming services use these subdomains (Wildcards) a lot ! Hope you're making progress !

**Comment by Ranger802004** [comment]
> How is this feature going !! It would greatly help me. I notice that streaming services use these subdomains (Wildcards) a lot ! Hope you're making progress !

It's on the back burner at the moment as I have some more pressing projects I have to work on but probably in the next month or two I can start developing all of the logic for this to be tested and if that succeeds I can implement it into a beta to further test.

**Comment by Ranger802004** [comment]
Can you share with me the location and contents of your adguardhome configuration file that specifies the AdguardHome log file? Also provide me a sample of the log file again? Thank you.

**Comment by Ranger802004** [comment]
After researching AdGuardHome I was not able to determine it as viable to use to track the logs as the log does not bind domains to IP address destinations, only the domain with the client requesting it.

**Comment by Ranger802004** [comment]
v3.0.0-beta1 has been released, you can read about it here: https://www.snbforums.com/threads/domain-vpn-routing-v3-0-0-beta1-release.92029/

**Comment by Ranger802004** [comment]
Requested feature is in current v3.0.0-beta1 and will be included in v3.0.0 final release, if you have any issues please open a new issue.  Thank you.

**Comment by romanlex** [comment]
@Ranger802004 I found solution how we can read and parse querylog from Adguard
https://github.com/AdguardTeam/AdGuardHome/discussions/4246#discussioncomment-9835834
```
{"T":"2024-10-15T21:53:04.085376711+03:00","QH":"app.slack.com","QT":"A","QC":"IN","CP":"","Upstream":"https://cloudflare-dns.com:443/dns-query","Answer":"lUaBoAABAAYAAAABA2FwcAVzbGFjawNjb20AAAEAAcAMAAEAAQAAACUABANEfKjADAABAAEAAAAlAAQDRK9iwAwAAQABAAAAJQAEA0SqmcAMAAEAAQAAACUABBKfxeHADAABAAEAAAAlAAQDRHxfwAwAAQABAAAAJQAENB3u1AAAKQTQAAAAAAAA","IP":"127.0.0.1","Result":{},"Elapsed":111182484,"AD":true}
```
Read and parse Answer when get Answer Address

**Comment by computersteve** [comment]
^ did this help @Ranger802004 meaning are you able to use this to maybe implement Adguard support ?

**Comment by Ranger802004** [comment]
> @Ranger802004 I found solution how we can read and parse querylog from Adguard [AdguardTeam/AdGuardHome#4246 (comment)](https://github.com/AdguardTeam/AdGuardHome/discussions/4246#discussioncomment-9835834)
> 
> ```
> {"T":"2024-10-15T21:53:04.085376711+03:00","QH":"app.slack.com","QT":"A","QC":"IN","CP":"","Upstream":"https://cloudflare-dns.com:443/dns-query","Answer":"lUaBoAABAAYAAAABA2FwcAVzbGFjawNjb20AAAEAAcAMAAEAAQAAACUABANEfKjADAABAAEAAAAlAAQDRK9iwAwAAQABAAAAJQAEA0SqmcAMAAEAAQAAACUABBKfxeHADAABAAEAAAAlAAQDRHxfwAwAAQABAAAAJQAENB3u1AAAKQTQAAAAAAAA","IP":"127.0.0.1","Result":{},"Elapsed":111182484,"AD":true}
> ```
> 
> Read and parse Answer when get Answer Address

The example log still shows the localhost IP as in the requesting device instead of the destination IP of the queried domain in that log example.

**Comment by Ranger802004** [comment]
I do see they are using a python script to get the data extract, it's possible but I'll have to look into it.

**Comment by Ranger802004** [comment]
So after some initial testing, there is some potential to implement this.  I will look at adding this as a feature soon.  Not being familiar with AdGuardHome I am now aware the Answer is a BASE64 string that can be parsed to get the data needed.

**Comment by romanlex** [comment]
Nice, its good news

**Comment by Ranger802004** [comment]
I have successfully built in AdGuardHome log querying in my developer build of Domain VPN Routing, I have successfully built and tested this for wildcard, non-wildcard domain entries as well as IPv4 and IPv6.  I used the python script you found and made some modifications to integrate it as well as another python script for converting IPv6 output properly.  These can be built into the core script as functions.  The requirements for AdGuardHome log querying would be Python3 installed, jq installed, and AdGuardHome being installed and actively running.

**Comment by Ranger802004** [comment]
Querying AdGuardHome log has been included in v3.0.2-beta1 that is now released on the Beta update channel.

**Comment by computersteve** [comment]
So there seems to be a bug ! I can no longer Query any policies.. They keep just getting stuck on the first domain in the policy and never changing..

**Comment by Ranger802004** [comment]
> So there seems to be a bug ! I can no longer Query any policies.. They keep just getting stuck on the first domain in the policy and never changing..

Are you using AdguardHome? If so, how large is the query log file? It may not be stuck it may be taking a long time to process each domain.  What if your query ASNs or a single policy?

**Comment by computersteve** [comment]
I am using AdGuard home but I am honestly not interested in it for this integration with your script. Don’t get me wrong it’s great you’re working on integrating it. I just upgraded to upgrade to the latest version just cause an update was available. Then all I did was try to query all my policies like I sometimes do, and instead of it working now all it does is stay at the first policy on the first domain, and never changes or finishes.

**Comment by computersteve** [comment]
I have my AdGuard setup based on the AMTM wizard I didn’t really customize it. How do I find out how big my query log file is ? However that will need to be addressed because I left it for while and it was stuck on one domain for like 10 minutes in eventually just closed the terminal.

**Comment by computersteve** [comment]
I guess what I’m saying I think it isn’t working. I kept it open for a while like 10 minutes and I specifically only queried a one domain policy called Roku. It stayed on the same domain for 10 minutes with nothing appearing to happen. So while it’s good you can disable it. Maybe it isn’t working for the people who actually want it.

**Comment by computersteve** [comment]
> > I am using AdGuard home but I am honestly not interested in it for this integration with your script. Don’t get me wrong it’s great you’re working on integrating it. I just upgraded to upgrade to the latest version just cause an update was available. Then all I did was try to query all my policies like I sometimes do, and instead of it working now all it does is stay at the first policy on the first domain, and never changes or finishes.
> 
> I can add a config option to disable the functionality. But verify it finishes all of the way through and completes.

so this is what my policy looks like: 

Policy Name: Roku
Interface: wan
Verbose Logging: Disabled
Private IP Addresses: Disabled
Add CNAMES: Not Configured
Domains:
googletv.web.roku.com


This is what is happening:::  I have created this video so you can see what is happening =) 
https://www.dropbox.com/s/y3mahsp0fzsxoki/vpnrouting.mov?dl=0

**Comment by Ranger802004** [comment]
> > > I am using AdGuard home but I am honestly not interested in it for this integration with your script. Don’t get me wrong it’s great you’re working on integrating it. I just upgraded to upgrade to the latest version just cause an update was available. Then all I did was try to query all my policies like I sometimes do, and instead of it working now all it does is stay at the first policy on the first domain, and never changes or finishes.
> > 
> > 
> > I can add a config option to disable the functionality. But verify it finishes all of the way through and completes.
> 
> so this is what my policy looks like:
> 
> Policy Name: Roku Interface: wan Verbose Logging: Disabled Private IP Addresses: Disabled Add CNAMES: Not Configured Domains: googletv.web.roku.com
> 
> This is what is happening::: I have created this video so you can see what is happening - I eventually killed the query manually because it would just stay like this for very long and the video would be way to long lol =) https://www.dropbox.com/s/y3mahsp0fzsxoki/vpnrouting.mov?dl=0

A couple things here:
1. In the error you get, it says there is a keyboard interrupt.  Did you hit Ctrl + C at some point during execution?
2. How large is your AdGuardHome query log file? Location: /opt/etc/AdGuardHome/data/querylog.json

**Comment by computersteve** [comment]
So yes I did have to eventually kill the process with ctrl + c cause the video would have been very long lol I left for over 20 minutes and it still didn't do anything -- 
My querylog.json = 3.8 gb --- That seems gigantic lol.. Why is a log file so big ? Is there a way to make it not keep such a large log file or is that the way adguard works ? My setup is pretty mush the default after using the installer from AMTM for adguard except for adding some list that I want. Does it have something to do with query log rotation?  I do notice this setting is set to 90 days.
<img width="562" alt="Screenshot 2024-10-28 at 10 57 28 AM" src="https://github.com/user-attachments/assets/7d24aa95-6346-4d60-909d-d71bb204da50">
<img width="1190" alt="Screenshot 2024-10-28 at 11 01 14 AM" src="https://github.com/user-attachments/assets/32b74067-977d-47f7-aa0e-642aba995b05">

**Comment by Ranger802004** [comment]
Try and reduce the log size, this is probably why it's taking so long.  In lab testing I'm working with a much smaller log file and it seems to take a few minutes still.  I'll probably make some optimizations to AdGuardHome integration due to this potentially causing long execution times.

**Comment by computersteve** [comment]
Yeah I think further optimizations are going to be needed with that.. The way it currently is I now no longer want to query my policies cause it takes so long lol --- How do I reduce the log size ? & what do you recommend 6 hours? or a custom time of ?

**Comment by Ranger802004** [comment]
> Yeah I think further optimizations are going to be needed with that.. The way it currently is I now no longer want to query my policies cause it takes so long lol --- How do I reduce the log size ? & what do you recommend 6 hours? or a custom time of ?

For this particular issue, I would set it smaller as that would be best.  As far as AdGuardHome recommendations I can't say what is optimal, I don't think it's necessary to run AdGuardHome just a log file for record keeping / investigative type tasks.

**Comment by computersteve** [comment]
So it seems like setting the smaller log size helps - Thanks !

**Comment by Ranger802004** [comment]
> So it seems like setting the smaller log size helps - Thanks !

I am adding a config option to enable / disable the AdGuardHome log querying functionality as well as I found an optimization that will help cut down some time.

**Comment by computersteve** [comment]
> v3.0.2-beta2 has been released on the beta channel. It includes an option to disable/enable AdGuardHome logging in the configuration menu, it is disabled by default. Additionally, some optimizations have been implemented with AdGuardHome logging including process optimization and log file checkpointing. The initial query of the log will have no checkpoint but after it sets a checkpoint it will only check new log entries after the checkpoint was set. The checkpoint only applies to querying all policies. Some additional prompts have been added during execution to have more insight to processing of querypolicy function.

Yeah as mentioned in a different bug report -- I can't seem to update properly --- meaning your script keeps thinking it isn't running and this is displayed: 

***Dev Mode is Enabled***
domain_vpn_routing is out of date - Current Version: v3.0.2-beta1 Available Version: v3.0.2-beta2
Do you want to update to the latest beta version? v3.0.2-beta2 ***Enter Y for Yes or N for No*** 
> Y
domain_vpn_routing: Update - domain_vpn_routing has been updated to version: v3.0.2-beta2
domain_vpn_routing: Restart - ***domain_vpn_routing is not running*** No Process ID Detected

& then it just loops  

It eventually updates but I gotta open and close the script a few times lol Just so you are aware of that =)

**Comment by Gundabadec** [comment]
It takes a long time to query all policies in default log file **v3.0.1**
**472.5M**  dnsmasq.log

**Comment by Ranger802004** [comment]
> It takes a long time to query all policies in default log file **v3.0.1** **472.5M** dnsmasq.log Can we optimize the process or show progress?

This has already been done in the current beta with visual prompts if manually running querypolicy.

**Comment by Ranger802004** [comment]
v3.0.2 has been released to resolve this issue.  Open a new GitHub issue for any additional issues or feature requests.
