### ISSUE TITLE
WF will not configure/status installed on AX11000 Pro

### ISSUE THREAD

**Issue by jgodfrey82** [Ranger802004/asusmerlin#30]
cannot get WF script to configure once installed.   

DEBUG log error over and over again:
Sep  5 21:28:43 wan-failover: Debug - failed to set WAN1GWIFNAME
Sep  5 21:28:43 wan-failover: Debug - failed to set WAN1GWIFNAME

I factory reset, formatted my usb, reinstalled swap entware and then tried WF install and I'm still getting the same hang when trying option 5 or option 1. 

My alias also doesn't seem to register as running wan-failover at cli just gives not found.

The only error I ever see other than hang at option 5 is during option 4 uninstall :
wan-failover - Uninstall: /jffs/scripts/wan-failover.sh deleted.
Command line is not complete. Try option "help"
Error: inet6 prefix is expected rather than "100".
awk: /jffs/configs/wan-failover.conf: No such file or directory

install log:
Do you want to install WAN Failover? ***Enter Y for Yes or N for No***
> y
Getting System Settings...
Successfully acquired System Settings
Getting WAN Parameters...
Successfully acquired WAN Parameters
Creating /jffs/configs/wan-failover.conf...
/jffs/configs/wan-failover.conf created successfully.
wan-event script already exists...
Adding wan-failover to wan-event...
wan-failover added to wan-event.
/jffs/configs/profile.add already exists...
wan-failover - Install: Creating Alias for /jffs/scripts/wan-failover.sh as wan-failover...
wan-failover - Install: Created Alias for /jffs/scripts/wan-failover.sh as wan-failover...
Creating Cron Job...
Created Cron Job
Dual WAN is Enabled.
ASUS Factory WAN Failover Disabled.
ASUS Factory Failback Disabled.
ASUS Factory DNS Probe Disabled.
Administration > System > Enable JFFS custom scripts and configs is enabled...

**Comment by Ranger802004** [comment]
It hangs there after the check for JFFS custom scripts and configs being enabled?

**Comment by jgodfrey82** [comment]
> It hangs there after the check for JFFS custom scripts and configs being enabled?

No sir, install completes, I launch using wf in amtm but if I try to configure or status is hangs, it will do some of the other options but without configuration it doesn't actually do anything and the error wan-failover: Debug - failed to set WAN1GWIFNAME just keeps logging over and over  again multiple times per second until I uninstall the script.

**Comment by Ranger802004** [comment]
So it's looping because it can't get a value from NVRAM for the WAN1 Gateway Interface, run the below commands on the router as well as tell me which version of ASUS Merlin you are running.

```
nvram get wan1_gw_ifname
nvram show | grep wan1_
```

**Comment by jgodfrey82** [comment]
> So it's looping because it can't get a value from NVRAM for the WAN1 Gateway Interface, run the below commands on the router as well as tell me which version of ASUS Merlin you are running.
> 
> ```
> nvram get wan1_gw_ifname
> nvram show | grep wan1
> ```
Running merlin 3004.388.8
Below command isn't showing values? 

admin@GT-AX11000_Pro-BB00:/tmp/home/root# nvram get wan1_gw_ifname
admin@GT-AX11000_Pro-BB00:/tmp/home/root# nvram show | grep wan1_
wan1_6rd_ip4size=
wan1_6rd_prefix=
wan1_6rd_prefixlen=
wan1_6rd_router=
wan1_auth_x=
wan1_auxstate_t=0
wan1_clientid=
wan1_clientid_type=0
wan1_desc=
wan1_dhcp_qry=1
wan1_dhcpenable_x=1
wan1_dhcpfilter_enable=1
wan1_dns=
wan1_dns1_x=
wan1_dns2_x=
wan1_dnsenable_x=1
wan1_enable=1
wan1_gateway=0.0.0.0
wan1_gateway_x=0.0.0.0
wan1_gw_mac=
wan1_heartbeat_x=
wan1_hostname=
wan1_hwaddr=
wan1_hwaddr_x=
wan1_hwname=
wan1_ifname=
wan1_ifname_x=eth0
wan1_ipaddr=0.0.0.0
wan1_ipaddr_x=0.0.0.0
wan1_is_usb_modem_ready=0
wan1_mroute=
wan1_mtu=1500
wan1_nat_x=1
wan1_netmask=0.0.0.0
wan1_netmask_x=0.0.0.0
wan1_phytype=
wan1_ppp_echo=1
wan1_ppp_echo_failure=10
wan1_ppp_echo_interval=6
wan1_pppoe_ac=
wan1_pppoe_auth=
wan1_pppoe_hostuniq=
wan1_pppoe_idletime=0
wan1_pppoe_ifname=
wan1_pppoe_mru=1492
wan1_pppoe_mtu=1492
wan1_pppoe_options_x=
wan1_pppoe_passwd=
wan1_pppoe_relay=0
wan1_pppoe_service=
wan1_pppoe_username=
wan1_pptp_options_x=
wan1_primary=0
wan1_proto=dhcp
wan1_proto_t=
wan1_realip_ip=
wan1_realip_state=0
wan1_route=
wan1_s46_dslite_mode=0
wan1_s46_ealen_x=0
wan1_s46_offset_x=6
wan1_s46_peer_x=
wan1_s46_prefix4_x=
wan1_s46_prefix4len_x=0
wan1_s46_prefix6_x=
wan1_s46_prefix6len_x=0
wan1_s46_psid_x=0
wan1_s46_psidlen_x=0
wan1_sbstate_t=0
wan1_state_t=0
wan1_unit=0
wan1_upnp_enable=1
wan1_vendorid=
wan1_vpndhcp=1
wan1_wins=
wan1_xgateway=0.0.0.0
wan1_xipaddr=0.0.0.0
wan1_xnetmask=0.0.0.0
size: 101509 bytes (95099 left)
admin@GT-AX11000_Pro-BB00:/tmp/home/root#

**Comment by Ranger802004** [comment]
Yea that's a problem, try disabling and re-enabling Dual WAN and see if it populates the values, do you have an interface selected in the GUI for WAN1?

**Comment by jgodfrey82** [comment]
> Yea that's a problem, try disabling and re-enabling Dual WAN and see if it populates the values, do you have an interface selected in the GUI for WAN1?

Yes I've done that, no change. wan1 selection is the 2.5/1g port.  I've already completely factory reset and the issue persists.  Is it Nvram issue I need to low level format or reset it?

**Comment by jgodfrey82** [comment]
Disable and re-enable dual wan reran Nvram commands and still all blank/zero

**Comment by Ranger802004** [comment]
Try changing the assigned interface to WAN1.

**Comment by jgodfrey82** [comment]
WAN1 is not an option, the dual wan interface options are 
1G/2.5G
10G 
USB
Ethernet LAN

**Comment by Ranger802004** [comment]
WAN1 is just a name for the 2nd WAN interface.  Just a select a different interface than the one you have currently selected.  What is the current option you have selected?

**Comment by jgodfrey82** [comment]
I have 1G/2.5G as option 1 and usb as option 2.

I just changed it to 1.5/2.5 for option 1 and ethernet for option 2, reinstalled wf and it still just freezes trying config and my log file filling with

Sep  8 12:15:01 wan-failover: Debug - failed to set WAN1GWIFNAME

**Comment by Ranger802004** [comment]
Yea, this is a strange issue with the router itself and an NVRAM issue.  Have you tried flashing it with ASUS recovery tool back to factory firmware and then reinstalling merlin?

**Comment by jgodfrey82** [comment]
No I haven't tried that. Strange that everything else works, it's a brand new router.  Will try that and see what it does

**Comment by Ranger802004** [comment]
Keep me posted

**Comment by jgodfrey82** [comment]
> Keep me posted

Alright that did it.. Getting recovery to install was a sob, but once I did that, reinstalled merlin and wf it's working fine.  Wondering if I could have just cleared Nvram with the wps button to get it but did a full recovery anyways.  Thank you I appreciate your time.

**Comment by Ranger802004** [comment]
Excellent news, I will go ahead and close out this issue.
