### ISSUE TITLE
DDNS dos not update on failback

### ISSUE THREAD

**Issue by michnovka** [Ranger802004/asusmerlin#31]
I have namecheap DDNS set up, and I noticed that when the WAN fail was detected (I unplugged primary WAN) the DDNS changed to my secondary WAN. But on failback, it did not. So now I am stuck for several hours on an outdated IP in DDNS.

**Comment by Ranger802004** [comment]
This isn't a direct feature that WAN Failover manages, these events should be triggered automatically.  Not really an issue as we don't have DDNS set up to manually update with WAN Failover, this would be more of a feature request to add that capability.
