### ISSUE TITLE
Domain VPN Routing + WireGuard

### ISSUE THREAD

**Issue by AirAlarm** [Ranger802004/asusmerlin#32]
Hello, I'm coming from SNB Forums, the problem is that the script doesn't seem to be routing traffic through the WireGuard connection. I'm also using the UDP trash hack for WireGuard to generate random connection port because of the local censorship. 

Router: RT-AX58U v1
Merlin: 3004.388.8_2

wgclient-start as follows:
```
#!/bin/sh

# Enable exit on error
set -e

# Function to generate a random number between 49152 and 65535
generate_random_port() {
    awk -v min=49152 -v max=65535 'BEGIN { srand(); print int(min + rand() * (max - min + 1)) }'
}

interface="wgc$1"
sleep 3
# Log the start of the script
logger -t WireGuardClient -p user.notice "Starting junk-udp-hack script"
logger -t WireGuardClient -p user.notice "Processing WG interface - $interface"

# Retrieve the server and port
wg_endpoint=$(wg show "$interface" endpoints 2>/dev/null || echo "")
if [ -z "$wg_endpoint" ]; then
    logger -s -t WireGuardClient -p user.err "Unable to retrieve endpoint for interface $interface" >&2
    exit 1
fi

wg_server=$(echo "$wg_endpoint" | awk '{print $2}' | cut -d':' -f1 2>/dev/null || echo "")
wg_port=$(echo "$wg_endpoint" | awk '{print $2}' | cut -d':' -f2 2>/dev/null || echo "")

if [ -z "$wg_server" ] || [ -z "$wg_port" ]; then
    logger -s -t WireGuardClient -p user.err "Unable to extract server or port for interface $interface" >&2
    exit 1
fi

# Generate a random message
message=$(dd if=/dev/urandom bs=228 count=5 2>/dev/null | tr -dc 'A-Za-z0-9')

# Generate a new random port and ensure it's not in use
l_port=$(generate_random_port)
while netstat -an | grep -qE '(^|[^0-9])'"$l_port"'([^0-9]|$)'; do
    logger -t WireGuardClient -p user.warn "Port $l_port is already in use. Generating new one"
    sleep 1
    l_port=$(generate_random_port)
done

logger -t WireGuardClient -p user.notice "Setting connection to WG server $wg_server:$wg_port from client's port $l_por>

# Send the message using socat
echo "$message" | socat - UDP-SENDTO:"$wg_server:$wg_port",sourceport="$l_port"

# Update the WireGuard interface with the new listen port
wg set "$interface" listen-port "$l_port"

logger -t WireGuardClient -p user.notice "Done"

sh /jffs/scripts/domain_vpn_routing.sh cron # domain_vpn_routing

sh /jffs/scripts/domain_vpn_routing.sh querypolicy all # domain_vpn_routing_queryall
```

I have created a single policy to test YouTube with (also blocked for me):

```
Policy Name: YouTube
Interface: wgc1
Verbose Logging: Enabled
Private IP Addresses: Disabled
Domains:
*.googlevideo.com
ggpht.com
googleapis.com
googleusercontent.com
googlevideo.com
gstatic.com
nhacmp3youtube.com
www.youtube.com
youtu.be
youtube.com
youtubei.googleapis.com
yt3.ggpht.com
yt4.ggpht.com
ytimg.com
ytimg.l.google.com
```

How can I share the log data with you so you could have a look into my case?
What kind of additional info would you need?

Thanks!

**Comment by JoyZzzzz** [comment]
This script bundle works fine for me.
Try using a newer version of the UDP Trash Hack script.

**Comment by Ranger802004** [comment]
The wildcard is not supported and I can see that causing an error in the current build. I am working to include wildcards for the next release.

**Comment by AirAlarm** [comment]
I have removed the wildcard and updated the UDP script. 
Still doesn’t seem to be working

**Comment by JoyZzzzz** [comment]
> Do I need to assign devices in the VPN Director for my WireGuard connection?

Only if you want to route all traffic through WireGuard without using a routing script

**Comment by AirAlarm** [comment]
> > Only if you want to route all traffic through WireGuard without using a routing script
> 
> 

And what if I want to use your script, is there any way I could track and troubleshoot the issue described above?

**Comment by Ranger802004** [comment]
Have you verified your VPN tunnel is working in general? Do you have other traffic you have routed to the tunnel working properly?

**Comment by AirAlarm** [comment]
> Have you verified your VPN tunnel is working in general? Do you have other traffic you have routed to the tunnel working properly?

Yes, I can assure you that my VPN tunnel is working. I have several devices in my home network assigned to this tunnel to route all traffic through it.

**Comment by Ranger802004** [comment]
v3.0.0-beta1 has been released, you can read about it here: https://www.snbforums.com/threads/domain-vpn-routing-v3-0-0-beta1-release.92029/

**Comment by AirAlarm** [comment]
> v3.0.0-beta1 has been released, you can read about it here: https://www.snbforums.com/threads/domain-vpn-routing-v3-0-0-beta1-release.92029/
> 
> Test on this new release and provide feedback.

I re-installed the script, same behavior upon update.
Now I receive this when I try to query my policy:

`/jffs/scripts/domain_vpn_routing.sh: line 40: WGC1IPV6ADDR: parameter not set`

**Comment by AirAlarm** [comment]
> v3.0.0-beta1 has been released, you can read about it here: https://www.snbforums.com/threads/domain-vpn-routing-v3-0-0-beta1-release.92029/
> 
> Test on this new release and provide feedback.

Now I receive this when I try to query my policy:

`/jffs/scripts/domain_vpn_routing.sh: line 40: WGC1IPV6ADDR: parameter not set`

**Comment by Ranger802004** [comment]
Are you using an RT-AC68U?

**Comment by AirAlarm** [comment]
> Are you using an RT-AC68U?

No, I'm on RT-AX58U v1

**Comment by Ranger802004** [comment]
A minor fix has been published, force an update and retry.

**Comment by AirAlarm** [comment]
> A minor fix has been published, force an update and retry.

Unfortunately, the behavior is the same. 
I created other policy for another blocked website, doesn't work.

**Comment by JoyZzzzz** [comment]
> I created other policy for another blocked website, doesn't work for me.

What site are you pushing into the script?

**Comment by AirAlarm** [comment]
> Which WireGuard client slot are you using?

WGC1

**Comment by AirAlarm** [comment]
> > I created other policy for another blocked website, doesn't work for me.
> 
> 
> 
> What site are you pushing into the script?

Policy Name: meduza
Interface: wgc1
Verbose Logging: Disabled
Private IP Addresses: Disabled
Domains:
meduza.io

**Comment by Ranger802004** [comment]
Please send the output of the following commands

`ip rule list`
`ip -6 rule list`
`ip route show  table wgc1`
`tracert -4 meduza.io`

**Comment by JoyZzzzz** [comment]
> Domains:
> meduza.io

This site uses protection/proxy from cloudflare. The Domain VPN Routing script does not work correctly on such sites and does not route them.

**Comment by JoyZzzzz** [comment]
> I just test added it to a policy using OVPN and it routed correctly over my VPN.

I tried several sites with proxy from cloudflare with routing in Wireguard, none of them worked. I checked it on my personal site as well.

**Comment by AirAlarm** [comment]
> Please send the output of the following commands
> 
> 
> 
> `ip rule list`
> 
> `ip -6 rule list`
> 
> `ip route show table wgc1`
> 
> `traceroute -4 meduza.io`
> 
> 

AirAlarm@RT-AX58U:/tmp/home/root# ip rule list
0:      from all lookup local
6000:   from all fwmark 0xa000/0xf000 lookup wgc1
11210:  from 192.168.50.38 lookup wgc1
11211:  from 192.168.50.45 lookup wgc1
11212:  from 192.168.50.29 lookup wgc1
11213:  from 192.168.50.44 lookup wgc1
11214:  from 192.168.50.23 lookup wgc1
32766:  from all lookup main
32767:  from all lookup default
AirAlarm@RT-AX58U:/tmp/home/root# ip -6 rule list
0:      from all lookup local
6000:   from all fwmark 0xa000/0xf000 unreachable
32766:  from all lookup main
AirAlarm@RT-AX58U:/tmp/home/root# ip route show table wgc1
0.0.0.0/1 dev wgc1 scope link 
default via 62.217.190.1 dev br101 
5.45.68.225 via 62.217.190.1 dev br101 
62.217.190.0/24 dev br101 proto kernel scope link src 62.217.190.202 
62.217.190.1 dev br101 proto kernel scope link 
89.207.216.1 via 62.217.190.1 dev br101 metric 1 
95.131.144.199 via 62.217.190.1 dev br101 metric 1 
127.0.0.0/8 dev lo scope link 
128.0.0.0/1 dev wgc1 scope link 
192.168.50.0/24 dev br0 proto kernel scope link src 192.168.50.1 
192.168.51.0/24 dev tun21 proto kernel scope link src 192.168.51.1 
239.0.0.0/8 dev br0 scope link 
AirAlarm@RT-AX58U:/tmp/home/root# tracert -4 meduza.io
-sh: tracert: not found

**Comment by Ranger802004** [comment]
> > Please send the output of the following commands
> > `ip rule list`
> > `ip -6 rule list`
> > `ip route show table wgc1`
> > `traceroute -4 meduza.io`
> 
> AirAlarm@RT-AX58U:/tmp/home/root# ip rule list 0: from all lookup local 6000: from all fwmark 0xa000/0xf000 lookup wgc1 11210: from 192.168.50.38 lookup wgc1 11211: from 192.168.50.45 lookup wgc1 11212: from 192.168.50.29 lookup wgc1 11213: from 192.168.50.44 lookup wgc1 11214: from 192.168.50.23 lookup wgc1 32766: from all lookup main 32767: from all lookup default AirAlarm@RT-AX58U:/tmp/home/root# ip -6 rule list 0: from all lookup local 6000: from all fwmark 0xa000/0xf000 unreachable 32766: from all lookup main AirAlarm@RT-AX58U:/tmp/home/root# ip route show table wgc1 0.0.0.0/1 dev wgc1 scope link default via 62.217.190.1 dev br101 5.45.68.225 via 62.217.190.1 dev br101 62.217.190.0/24 dev br101 proto kernel scope link src 62.217.190.202 62.217.190.1 dev br101 proto kernel scope link 89.207.216.1 via 62.217.190.1 dev br101 metric 1 95.131.144.199 via 62.217.190.1 dev br101 metric 1 127.0.0.0/8 dev lo scope link 128.0.0.0/1 dev wgc1 scope link 192.168.50.0/24 dev br0 proto kernel scope link src 192.168.50.1 192.168.51.0/24 dev tun21 proto kernel scope link src 192.168.51.1 239.0.0.0/8 dev br0 scope link AirAlarm@RT-AX58U:/tmp/home/root# tracert -4 meduza.io -sh: tracert: not found

I edited the last command as I typed in the windows binary by accident instead of linux/unix one, redo the last command please.

**Comment by Ranger802004** [comment]
> > > > I edited the last command as I typed in the windows binary by accident instead of linux/unix one, redo the last command please.
> 
> `AirAlarm@RT-AX58U:/tmp/home/root# traceroute -4 meduza.io traceroute to meduza.io (188.114.98.224), 30 hops max, 38 byte packets 1 10.8.1.0 (10.8.1.0) 172.915 ms 184.550 ms 170.939 ms 2 172.29.172.1 (172.29.172.1) 160.221 ms 165.610 ms 169.608 ms 3 185.238.169.20 (185.238.169.20) 172.798 ms * 184.539 ms 4 * * * 5 10.40.20.1 (10.40.20.1) 169.064 ms 167.579 ms 164.204 ms 6 * * * 7 be3761.rcr61.ley01.atlas.cogentco.com (154.25.15.105) 157.964 ms 161.721 ms 170.416 ms 8 be4541.ccr42.ams03.atlas.cogentco.com (154.54.72.53) 187.161 ms be4540.ccr41.ams03.atlas.cogentco.com (154.54.72.21) 181.115 ms be4541.ccr42.ams03.atlas.cogentco.com (154.54.72.53) 189.349 ms 9 * be2020.rcr21.b021535-1.ams03.atlas.cogentco.com (154.54.56.166) 182.093 ms be2175.rcr21.b021535-1.ams03.atlas.cogentco.com (154.54.61.42) 174.725 ms 10 149.11.203.154 (149.11.203.154) 173.805 ms 183.927 ms 149.14.83.58 (149.14.83.58) 178.199 ms 11 141.101.65.103 (141.101.65.103) 179.232 ms 141.101.65.14 (141.101.65.14) 181.852 ms 141.101.65.93 (141.101.65.93) 183.851 ms 12 188.114.98.224 (188.114.98.224) 167.330 ms 166.518 ms 164.919 ms`

Is 10.8.1.0 your VPN Gateway or local router gateway?

**Comment by AirAlarm** [comment]
> Is 10.8.1.0 your VPN Gateway or local router gateway?

It should be my VPN gateway. The local router gateway is 192.168.50.1

**Comment by Ranger802004** [comment]
> > Is 10.8.1.0 your VPN Gateway or local router gateway?
> 
> It should be my VPN gateway. The local router gateway is 192.168.50.1

Where do you notice the traffic is still routing over your WAN interface instead of the VPN?  When you actually load the page? I assume you are being met with a block page?

**Comment by Ranger802004** [comment]
That website appears to be using cdnjs.cloudflare.com which is a CDN, you may need to add this domain to your policy to get that traffic for CloudFlare over your VPN as well.

**Comment by AirAlarm** [comment]
> Where do you notice the traffic is still routing over your WAN interface instead of the VPN?  When you actually load the page? I assume you are being met with a block page?

Yes, when I try to load the page, and no, I'm actually don't get a block page, I'm getting Err_Connection_Timed_Out

**Comment by Ranger802004** [comment]
> That website appears to be using cdnjs.cloudflare.com which is a CDN, you may need to add this domain to your policy to get that traffic for CloudFlare over your VPN as well.

Try this

**Comment by AirAlarm** [comment]
> > That website appears to be using cdnjs.cloudflare.com which is a CDN, you may need to add this domain to your policy to get that traffic for CloudFlare over your VPN as well.
> 
> 
> 
> Try this

Added this domain to the policy 

Policy Name: meduza
Interface: wgc1
Verbose Logging: Disabled
Private IP Addresses: Disabled
Domains:
cdnjs.cloudflare.com
meduza.io

Getting Err_Connection_Timed_Out

**Comment by Ranger802004** [comment]
Did you perform a query policy after adding it?

**Comment by Ranger802004** [comment]
Do you have IPv6 configured?

**Comment by AirAlarm** [comment]
> Did you perform a query policy after adding it?

Yes, I did

**Comment by AirAlarm** [comment]
> Do you have IPv6 configured?

It's on by default, did not touch anything. 

![image](https://github.com/user-attachments/assets/dba0a062-695a-494b-ba5c-010114d44532)

**Comment by Ranger802004** [comment]
Turn it off if you're not using it.

**Comment by AirAlarm** [comment]
> Turn it off if you're not using it.

Turned IPv6 off, no luck.

**Comment by JoyZzzzz** [comment]
@AirAlarm 
Please execute two commands:
nslookup meduza.io 77.88.8.88:53
nslookup meduza.io 77.88.8.88:1253

**Comment by JoyZzzzz** [comment]
@Ranger802004 
Installing the new 3.0 script breaks the UDP Trash Hack for WireGuard script. With version 2.1.3, everything worked fine.

**Comment by Ranger802004** [comment]
> @Ranger802004 
> 
> Installing the new 3.0 script breaks the UDP Trash Hack for WireGuard script. With version 2.1.3, everything worked fine.

Trying to think what would cause that to break, this update doesn't change anything regarding the actual connection aspect of WireGuard.  Can you do some basic troubleshooting?

**Comment by AirAlarm** [comment]
> @AirAlarm Please execute two commands: nslookup meduza.io 77.88.8.88:53 nslookup meduza.io 77.88.8.88:1253

AirAlarm@RT-AX58U:/tmp/home/root# nslookup meduza.io 77.88.8.88:53
Server:    77.88.8.88
Address 1: 77.88.8.88 safe.dns.yandex.ru

Name:      meduza.io
Address 1: 188.114.98.229
Address 2: 188.114.99.229
Address 3: 2a06:98c1:3122:e000::5
Address 4: 2a06:98c1:3123:e000::5
AirAlarm@RT-AX58U:/tmp/home/root# nslookup meduza.io 77.88.8.88:1253
Server:    77.88.8.88
Address 1: 77.88.8.88 safe.dns.yandex.ru

Name:      meduza.io
Address 1: 188.114.99.229
Address 2: 188.114.98.229
Address 3: 2a06:98c1:3123:e000::5
Address 4: 2a06:98c1:3122:e000::5

**Comment by AirAlarm** [comment]
> @Ranger802004 Installing the new 3.0 script breaks the UDP Trash Hack for WireGuard script. With version 2.1.3, everything worked fine.

What's your client log status for WireGuard client? It is working fine by me even on 3.0 beta

**Comment by AirAlarm** [comment]
@Ranger802004 how can I verify what version I'm on? 

![image](https://github.com/user-attachments/assets/7c9006d8-36d4-4e7e-897e-ad76e99cf07c)

And that's what I get if try to update:

![image](https://github.com/user-attachments/assets/f9a00c8e-156c-4208-999e-bdae7aa4e812)

**Comment by Ranger802004** [comment]
It looks like it updated but your existing session still has the old version loaded, close out the script and restart it and check updates again.

**Comment by AirAlarm** [comment]
> It looks like it updated but your existing session still has the old version loaded, close out the script and restart it and check updates again.

If by restart you mean to (e)xit and to start the script again by running "domain_vpn_routing", then it shows the same message for me.

```
***Dev Mode is Enabled***
domain_vpn_routing is out of date - Current Version: v2.2.0-beta1 Available Version: v3.0.0-beta1
Do you want to update to the latest beta version? v3.0.0-beta1 ***Enter Y for Yes or N for No***
```

**Comment by Ranger802004** [comment]
> > It looks like it updated but your existing session still has the old version loaded, close out the script and restart it and check updates again.
> 
> If by restart you mean to (e)xit and to start the script again by running "domain_vpn_routing", then it shows the same message for me.
> 
> ```
> ***Dev Mode is Enabled***
> domain_vpn_routing is out of date - Current Version: v2.2.0-beta1 Available Version: v3.0.0-beta1
> Do you want to update to the latest beta version? v3.0.0-beta1 ***Enter Y for Yes or N for No***
> ```

Are you answer with "y" and hitting Enter when it asks if you want to update?

**Comment by AirAlarm** [comment]
> Are you answering with "y" and hitting Enter when it asks if you want to update?

Yes I am, and afterwards it still offers to update.

**Comment by dorner365** [comment]
I'm seeing the same update from 2.2.0-beta1 issue. Also, related (maybe) amtm is stuck at version 2.2.0.

**Comment by Ranger802004** [comment]
I tested this, I downgraded to v2.1.3, updated to v3.0.0-beta1 and it successfully installed.  Make sure you have Dev mode enabled and after the upgrade Ctrl + C out of the script and relaunch to verify.

**Comment by Ranger802004** [comment]
> I tested this, I downgraded to v2.1.3, updated to v3.0.0-beta1 and it successfully installed. Make sure you have Dev mode enabled and after the upgrade Ctrl + C out of the script and relaunch to verify.

Actually I see the problem, it's upgrading but a variable is not set properly so it thinks it is an older build.

**Comment by Ranger802004** [comment]
v3.0.0-beta2 has been released to fix the beta update channel issue.  After you update make sure you Ctrl + C out of Domain VPN Routing and then check for updates to verify it is up to date.

**Comment by Ranger802004** [comment]
I use IPFoo browser add on in chrome to do domain discovery.

**Comment by AirAlarm** [comment]
> I use IPFoo browser add on in chrome to do domain discovery.

Thanks, I will have a look.

Last question (hopefully). How do I enable DNS logging? Honestly tried googling and didn't find the answer.
I think I need to use wildcards for YouTube in order to make it work.

**Comment by AirAlarm** [comment]
I checked with other devices on my home network, seems like I false verified the script to be working for me. Will do more testing and come back with feedback.

**Comment by dorner365** [comment]
The update issue (in app and amtm) is fixed now. Thank you!

**Comment by AirAlarm** [comment]
So I've ended up with re-installing the script, adding one policy for meduza.io. 
This is the screen I get when I try to load meduza.io:
![image](https://github.com/user-attachments/assets/a6a56b1c-2030-4e91-a3d8-5eba11052edf)

Found out that if try to run wgclient-start command, it tries to run firewall-start script, but it's not created. Should I configure something else additionally for the script to actually run?

```
AirAlarm@RT-AX58U:/jffs/scripts# /jffs/scripts/wgclient-start 1
grep: /jffs/scripts/firewall-start: No such file or directory
domain_vpn_routing: Cron - Checking if Cron Job is Scheduled
Cron Job already exists
grep: /jffs/scripts/firewall-start: No such file or directory
Query Policy: meduza
```

**Comment by Ranger802004** [comment]
> So I've ended up with re-installing the script, adding one policy for meduza.io and cdnjs.cloudflare.com to test if it works. This is the screen I get when I try to load meduza.io: ![image](https://private-user-images.githubusercontent.com/47337303/373809900-a6a56b1c-2030-4e91-a3d8-5eba11052edf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwODA4NDQsIm5iZiI6MTcyODA4MDU0NCwicGF0aCI6Ii80NzMzNzMwMy8zNzM4MDk5MDAtYTZhNTZiMWMtMjAzMC00ZTkxLWEzZDgtNWViYTExMDUyZWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDIyMjIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZTVhZjFlODA3NjE0YTExNmZjZjllNTFjODM2ZmYxYmFlMDNhNDg5ZWZmOTdlMDA4OTUyNDgyOTc4ZTZiZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6x7NaAU4Re9Hw52CQIgAvVEQUfqCww1Fu21ThcQ-lBM) Or: ![image](https://private-user-images.githubusercontent.com/47337303/373816848-0d917d45-be4f-45db-b9d2-b0f5d0532e73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwODA4NDQsIm5iZiI6MTcyODA4MDU0NCwicGF0aCI6Ii80NzMzNzMwMy8zNzM4MTY4NDgtMGQ5MTdkNDUtYmU0Zi00NWRiLWI5ZDItYjBmNWQwNTMyZTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDIyMjIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMzc4NzM0ZTE1ZWU5NDIwOTUxYjg4Y2Q3ZTZmMDk4Y2VjYTNiMTBhNDc4YjBlODBkYTIyNzE5NGI4MTFhOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lYaNGSa9M1z2ITn3r851IrKnoMsLuu2bDkqbj3124r8)
> 
> Found out that if try to run wgclient-start command, it tries to run firewall-start script, but it's not created. Should I configure something else additionally for the script to actually run?
> 
> ```
> AirAlarm@RT-AX58U:/jffs/scripts# /jffs/scripts/wgclient-start 1
> grep: /jffs/scripts/firewall-start: No such file or directory
> domain_vpn_routing: Cron - Checking if Cron Job is Scheduled
> Cron Job already exists
> grep: /jffs/scripts/firewall-start: No such file or directory
> Query Policy: meduza
> ```
> 
> P.S.: I also have a pi.hole in my local network set up. Could it somehow affect the functionality of the script?

I had similar issues as this when using WireGuard and switched over to OpenVPN and no longer had those issues, I don't think Pi hole will have any issues as long as your router can retrieve queries and/or if you have dns logging it is able to see the logs from the log file.

**Comment by AirAlarm** [comment]
> I had similar issues as this when using WireGuard and switched over to OpenVPN and no longer had those issues, I don't think Pi hole will have any issues as long as your router can retrieve queries and/or if you have dns logging it is able to see the logs from the log file.

I would happily use OpenVPN if it wasn't blocked for me. Or any other stronger protocol if it was supported by AsusWRT firmware.

**Comment by Ranger802004** [comment]
When Domain VPN Routing configured domains aren't working, do you have other traffic that is traversing your WireGuard VPN? Can you do some traceroutes comparing the 2?

**Comment by AirAlarm** [comment]
> When Domain VPN Routing configured domains aren't working, do you have other traffic that is traversing your WireGuard VPN? Can you do some traceroutes comparing the 2?

Here is a traceroute from a device that is not forced to use VPN connection:

```
traceroute to meduza.io (104.18.1.79) , 5 relative hops max, 52 byte packets
   1 router.server.com (192.168.50.1) 4.993 ms 2806.348 ms 2828.639 ms
   2 10.8.1.0 (10.8.1.0) 47.180 ms 56.782 ms 59.320 ms
   3 172.29.172.1 (172.29.172.1) 47.818 ms 55.752 ms 58.184 ms
   4 185.238.169.20 (185.238.169.20) 47.827 ms 786.072 ms 790.454 ms
   5 37.1.216.1 (37.1.216.1) 60.042 ms 502.034 ms 507.095 ms
   6 10.40.20.1 (10.40.20.1) 48.778 ms 57.577 ms 60.843 ms
   7  * * *
   8 154.25.15.105 (154.25.15.105) 56.595 ms 1244.993 ms 1251.280 ms
   9 154.54.72.53 (154.54.72.53) 53.668 ms 512.476 ms 515.751 ms
 10 154.54.61.42 (154.54.61.42) 54.016 ms 194.484 ms 201.274 ms
 11  * * *
 12 141.101.65.2 (141.101.65.2) 53.639 ms 371.263 ms 373.572 ms
 13 104.18.1.79 (104.18.1.79) 52.041 ms 482.487 ms 485.040 ms
```

And here with same the VPN connection forced: 
```
traceroute to meduza.io (188.114.98.233) , 5 relative hops max, 52 byte packets
 12 141.101.65.99 (141.101.65.99) 51.225 ms
   1 router.server.com (192.168.50.1) 5.860 ms 2098.035 ms 2105.203 ms
   2 10.8.1.0 (10.8.1.0) 46.584 ms 49.262 ms 51.518 ms
   3 172.29.172.1 (172.29.172.1) 47.402 ms 50.096 ms 52.697 ms
   4 185.238.169.20 (185.238.169.20) 47.414 ms 50.023 ms 52.346 ms
   5 37.1.216.1 (37.1.216.1) 66.182 ms 69.281 ms 72.122 ms
   6 10.40.20.1 (10.40.20.1) 47.097 ms 49.923 ms 53.037 ms
   7  * * *
   8 154.25.15.105 (154.25.15.105) 55.396 ms 62.054 ms 68.440 ms
   9 154.54.72.21 (154.54.72.21) 51.742 ms 56.539 ms 61.056 ms
 10 154.54.56.166 (154.54.56.166) 54.132 ms 58.390 ms 63.113 ms
 11  * * *
 12 141.101.65.113 (141.101.65.113) 66.530 ms 99.630 ms 104.052 ms
 13 188.114.98.233 (188.114.98.233) 53.436 ms 841.823 ms 846.455 ms
```

**Comment by Ranger802004** [comment]
So it's routing properly....hmmm possibly could be Pi Hole...can you bypass and test Pi Hole?

**Comment by AirAlarm** [comment]
> So it's routing properly....hmmm possibly could be Pi Hole...can you bypass and test Pi Hole?

I have temporary disabled PiHole in my router to not to use it as custom DNS resolver.
Looks like that it really might be the source of my issue. 
But I don't get a consistent working behavior with the script. For simple blocked websites, such as meduza.io, I got it to work. 
Here's the tracert from test Windows machine with VPN off, the site loads: 

```
 Tracing route to meduza.io [188.114.99.229]
over a maximum of 30 hops:

  1     5 ms     5 ms     7 ms  RT-AX58U.local [192.168.50.1]
  2    48 ms    49 ms    64 ms  10.8.1.0
  3    51 ms    48 ms    49 ms  172.29.172.1
```

But if I try to traceroute YouTube, I don't always get my VPN IP address as the second hop. For "youtube.com" it works, but looks like the wildcard domains are not routed properly. I have even queried the policy multiple times in order to accumulate additional IPs:

```
Tracing route to googlevideo.com [64.233.163.106]
over a maximum of 30 hops:

  1     1 ms    <1 ms    <1 ms  RT-AX58U.local [192.168.50.1]
  2     4 ms     2 ms     2 ms  62.217.190.1
  3     5 ms     7 ms     2 ms  89.207.216.18
  4     *        5 ms     3 ms  142.250.160.102
  5     4 ms     3 ms     7 ms  209.85.250.43
```
 
I have waited awhile, and tried again, with different IP from the domain it worked:

```
Tracing route to googlevideo.com [74.125.131.106]
over a maximum of 5 hops:

  1     5 ms     5 ms     1 ms  RT-AX58U.local [192.168.50.1]
  2    45 ms    47 ms    46 ms  10.8.1.0
  3    56 ms    47 ms    50 ms  172.29.172.1
  4    47 ms    48 ms    44 ms  185.238.169.20
  5    60 ms    47 ms    48 ms  37.1.216.1
```

**Comment by Ranger802004** [comment]
Test on v3.0.0-beta3 please that was released today.

**Comment by AirAlarm** [comment]
> Test on v3.0.0-beta3 please that was released today.

I have been testing beta3 for a couple of days. Can confirm that the behavior with YouTube persists, some videos would load, some not. I think that it is somehow related with Google having a lot of domains and IPs for *.googlevideo.com. I have queried manually the YouTube policy until I don't get the "new IPs detected" message anymore, but some videos are still not loading.

**Comment by Ranger802004** [comment]
> > Test on v3.0.0-beta3 please that was released today.
> 
> I have been testing beta3 for a couple of days. Can confirm that the behavior with YouTube persists, some videos would load, some not. I think that it is somehow related with Google having a lot of domains and IPs for *.googlevideo.com. I have queried manually the YouTube policy until I don't get the "new IP Addresses detected" message anymore, but some videos are still not loading.
> 
> I found the IP address ranges for YouTube. Is it possible to add them to the policy?
> 
> `8.8.4.0/24, 8.8.8.0/24, 8.34.208.0/20, 8.35.192.0/20, 23.236.48.0/20, 23.251.128.0/19, 34.0.0.0/10, 35.184.0.0/13, 35.192.0.0/14, 35.196.0.0/15, 35.198.0.0/16, 35.199.0.0/17, 35.199.128.0/18, 35.200.0.0/13, 35.208.0.0/12, 64.18.0.0/20, 64.233.160.0/19, 66.102.0.0/20, 66.249.64.0/19, 70.32.128.0/19, 72.14.192.0/18, 74.114.24.0/21, 74.125.0.0/16, 104.132.0.0/23, 104.133.0.0/23, 104.134.0.0/15, 104.156.64.0/18, 104.237.160.0/19, 108.59.80.0/20, 108.170.192.0/18, 108.177.0.0/15, 130.211.0.0/16, 136.112.0.0/12, 142.250.0.0/15, 146.148.0.0/17, 162.216.148.0/22, 162.222.176.0/21, 172.110.32.0/21, 172.217.0.0/16, 172.253.0.0/16, 173.194.0.0/16, 173.255.112.0/20, 192.158.28.0/22, 192.178.0.0/15, 193.186.4.0/24, 199.36.154.0/23, 199.36.156.0/24, 199.192.112.0/22, 199.223.232.0/21, 207.223.160.0/20, 208.65.152.0/22, 208.68.108.0/22, 208.81.188.0/22, 208.117.224.0/19, 209.85.128.0/17, 216.58.192.0/19, 216.239.32.0/19, 216.239.36.0/24, 216.239.38.0/23, 216.239.40.0/22, 34.64.0.0/10, 34.128.0.0/10, 142.251.141.46/32, 212.188.34.209/32, 172.217.169.138/32, 142.250.187.106/32, 142.250.186.33/32, 172.217.17.238/32, 172.217.20.78/32, 142.250.185.238/32, 74.125.156.170/32, 185.38.0.76/32, 212.188.34.207/32, 108.177.14.138/32, 142.251.40.139/32, 142.251.40.102/32, 108.177.14.113/32, 142.251.40.138/32, 142.250.74.78/32, 142.251.141.145/32, 142.250.74.110/32, 142.251.40.103/32, 142.250.74.46/32, 108.177.97.78/32, 142.250.74.14/32, 142.250.74.78/32`

You can add the IP ranges to the traditional VPN Director rules that exist within the firmware.  What you can do is keep identifying the subdomains used by google and keep adding them to your policy as well as keep using youtube and let the querypolicy function pick them up from dnsmasq logging passively over time.

**Comment by AirAlarm** [comment]
> You can add the IP ranges to the traditional VPN Director rules that exist within the firmware. 

Correct me if I'm wrong, but this works only for OpenVPN configuration.

**Comment by AirAlarm** [comment]
@Ranger802004 thank so much you for your support! 
I finally got it to work.
