### ISSUE TITLE
Setname is too long, max 31 characters.

### ISSUE THREAD

**Issue by JoyZzzzz** [Ranger802004/asusmerlin#33]
The length of the configuration files for the asus router is no more than 31 characters. 
The default script creates DomainVPNRouting--ipv4, which is already 22 characters. No more than 9 characters are left for the policy being created, which is very inconvenient. If the policy has more characters, then iptables will return an error when processing. 
Is it possible to shorten the name "DomainVPNRouting"?

**Comment by Ranger802004** [comment]
That is something I'm looking into for next release.

**Comment by Ranger802004** [comment]
I have a working implementation of allowing up to 24 characters in my current dev build, I reduced the prefix names of the IPSets to allow this and built in logic to handle switching the existing policies over without a reboot.

**Comment by Ranger802004** [comment]
v3.0.0-beta1 has been released, you can read about it here: https://www.snbforums.com/threads/domain-vpn-routing-v3-0-0-beta1-release.92029/

**Comment by Ranger802004** [comment]
Requested feature is in current v3.0.0-beta1 and will be included in v3.0.0 final release, if you have any issues please open a new issue.  Thank you.
