### ISSUE TITLE
[Feature Request] Bulk add domains

### ISSUE THREAD

**Issue by JoyZzzzz** [Ranger802004/asusmerlin#34]
When creating a policy, a file policy_***_domainlist is created
I would like to be able to add and delete several domains at once by list manually without using the adddomain command. And so that the querypolicy and deletedomain commands could work normally with domains added this way.

**Comment by Ranger802004** [comment]
There are instructions for this currently in the readme.  At this time there are no plans to expand on this given the current method works ok.
