### ISSUE TITLE
DomainVPNRouting: Compatibility issue with old models (with 2 OpenVPN clients only)

### ISSUE THREAD

**Issue by tarek-zy** [Ranger802004/asusmerlin#35]
I have two old (but very popular) routers, model RT-AC68U and DSL-AC68U. I guess it is worth fixing this issue in the original script for everyone, because this issue prevents installing or using the original script entirely, and a beginner might not be able to do a manual fix at all.

Currently, the script immediately tries to get system parameters for OpenVPN clients 3, 4, and 5, which are not present by design at all in RT-AC68U, DSL-AC68U, and some other old models (they're documented in official Merlin). So, when the script tries to get these parameters without a prior check whether they're available or not, the script never finishes executing which prevents it from installing or running normally without manually editing the script for these models!

However, I had to edit the original code and remove all related lines to get it to work on both my routers since I started using the script a few months ago. To fix this, I deleted all lines related to the missing OpenVPN clients (3, 4 and 5), where the script gets all system parameters. The first line for OVPNC3 is at #4564 down till the last line for OVPNC5 at #4644 from file domain_vpn_routing.sh

Note: line numbers are specific to the latest version of the script (2.1.3), as I used no other version than this.

**Comment by Ranger802004** [comment]
Do you have 5 wireguard slots?

**Comment by tarek-zy** [comment]
No, RT-AC68U doesn't and won't support WireGuard at all according to RMerlin at SNBForums:
https://www.snbforums.com/threads/vpn-director.85669/post-853627

**Comment by Ranger802004** [comment]
I have an initial implementation of a fix for this issue in my current dev build that will be included in the next release.

**Comment by tarek-zy** [comment]
Is it possible to switch to the development branch by a command within your script? I'm more than happy to test this initial implementation.
I'm open to updating the script file too, if there is no update process available!

**Comment by Ranger802004** [comment]
The beta channel is where the script updates are deployed first, you would enable Dev Mode in the configuration menu to receive beta channel updates.  This particular update hasn't been deployed that channel yet although I anticipate to update soon.

**Comment by tarek-zy** [comment]
I'm looking forward to getting the update. Would you please notify me whenever it's available?

**Comment by Ranger802004** [comment]
I have fixed the issue with the VPN Client slot limitation but I think you are still going to have issues with the ip binary being out of date.

**Comment by tarek-zy** [comment]
Correct!
Anyway, I didn't make any changes to the script regarding the ip binary issue. I'm still researching a solution.
So, a fix for the OpenVPN limitation right now is totally enough for me.

**Comment by Ranger802004** [comment]
If you come up with something please share your findings.

**Comment by tarek-zy** [comment]
Yeah, that's for sure!
I'll wait until tomorrow to contact maurer at GitHub, maybe play with building the package myself, or we might get a more useful answer on my latest Entware thread at SNBForums

**Comment by Ranger802004** [comment]
v3.0.0-beta1 has been released, you can read about it here: https://www.snbforums.com/threads/domain-vpn-routing-v3-0-0-beta1-release.92029/

**Comment by tarek-zy** [comment]
Congrats on your new major release!
I'll do my best to start testing this beta within 24 hours. Will keep you always up to date regarding testing and the IP utility issue

**Comment by tarek-zy** [comment]
Sorry for my late update, I had an issue with my router and I put it out of service in my network temporarily. It will be ready by tomorrow and I'll start testing the beta version as soon as I get it running again. Sorry again!

**Comment by Ranger802004** [comment]
> Sorry for my late update, I had an issue with my router and I put it out of service in my network temporarily. It will be ready by tomorrow and I'll start testing the beta version as soon as I get it running again. Sorry again!

I think you're going to find yourself dead in the water until you resolve the ip binary version.

**Comment by tarek-zy** [comment]
Hello again,
I just upgraded the script on my RT-AC68U to the beta release, but unfortunately, I'm unable to use the script at all now as it requires a newer **ip** binary now.

I want to confirm to you that the script was working normally and routing totally fine in the previous release (2.1.3). So, I believe there's no need at all to exclude these models from using the next release. I'd suggest showing only a warning message instead, while keep it working normally just like in version 2.1.3

Additionally, I guess you already noticed at SNBForums that I started a new effort to get the **ip-full** package updated for my router models.

However, I just made another modification to the script on my DSL-AC68U to avoid using system binaries by commenting the respective lines in the script, thus using the Entware binaries. Well, at least they're a bit newer than the built-in ones!

I'm going to downgrade the script again now for my RT-AC68U, hoping to allow it to work for my router models in the next beta. Sorry for the late feedback!

**Comment by tarek-zy** [comment]
FYI, I just ended up commenting the lines that are responsible for checking the IP binary so that the script runs again.

Now, I can confirm that beta 2 version is working fine and my reported issue of OpenVPN 2 clients limit is fixed, the script no longer gets stuck when getting system parameters.

**Comment by Ranger802004** [comment]
> FYI, I just ended up commenting the lines that are responsible for checking the IP binary so that the script runs again.
> 
> Now, I can confirm that beta 2 version is working fine and my reported issue of OpenVPN 2 clients limit is fixed, the script no longer gets stuck when getting system parameters.

I'm not sure how it's making it through the different functions with the limitations or it's possibly creating a ton of duplicated rules potentially because the part of the binary that doesn't work is the logic used to check if things exist such as IP rules, etc.  While this may work it's definitely not a clean or reliable solution, I can look at additional workarounds using the Entware current binary available to see if I can make it work and allow it to dynamically use that one if the system default is not sufficient.

**Comment by tarek-zy** [comment]
I totally agree that it's not a clean or reliable solution. Can I help with figuring out if it's actually creating duplicated rules?

I guess what is making the script work for me is that I have a small number of domains in my only policy

**Comment by Ranger802004** [comment]
Look at the commands

`ip rule list`
`ip -6 rule list`

**Comment by tarek-zy** [comment]
Positive! Too many duplicates. From my understanding, each query makes another duplicate set of rules

**Comment by Ranger802004** [comment]
Yea I figured that was the case, I have a potential workaround I can test and try and implement for the older binaries but no guarantees because I don't know if I can replicate all of the current commands into the older binary, I will test using the entware version as it seems to be similar to the one you have on the RT-AC68U.  I will go ahead and reopen the issue and will update once I have an update.

**Comment by tarek-zy** [comment]
From a software engineering perspective, I'd go with a solution that is applicable for all binary versions, upgrading the whole application.

Please let me suggest that you output "ip rule list" command to a text file or a variable, then extract all interfaces with their respective rules into structured data. Then, you could compare the resulting data with the newer domain queries.

If the implementation would be much easier using arrays (or maybe some other data structure), I don't think users would mind adding a small library (such as "bash") from Entware.

I'm open for more developing discussions so that you avoid implementing something specific to the very old models, which eventually will be totally deprecated within a couple of years.

**Comment by Ranger802004** [comment]
Update to v3.0.0-beta3 and test please.

Release Notes:
v3.0.0-beta3 - 10/09/2024
Enhancements:
- Added functionality to support wildcards for subdomains.  Example: *.example.com ***Requires DNS Logging to be enabled***
- Added DNS Overrides for VPN Client interfaces, when a policy is configured with a specific interface it will use the system default DNS Server unless a DNS override is configured for that specific interface in the configuration menu.
- Domain queries will now utilize dig if it is installed and will bypass use of nslookup.
- If dig is installed, a policy can be configured to allow CNAMES of domains to be added to the policy domain list automatically during query execution.  This is disabled by default for existing policies and can be enabled using the editpolicy function.
- IP Version will now be displayed under System Information located in the Configuration menu.

Fixes:
- Reduced names of IPSets to allow policy names to have a max length of 24 characters.
- Fixed issue that caused RT-AC68U and DSL-AC68U to lock up on execution due to limitation of 2 OpenVPN Client slots.
- Domain VPN Routing will now check the IP version and operate in a compability mode for older versions.  If an optional binary is installed Domain VPN Routing will test and use the newer version of the ip binary between the system and optional binary.
- Fixed an issue with beta update channel.
- Fixed an issue where ip rules were not being deleted when an unreachable rule was being created to block traffic for a VPN interface being down.
- Fixed minor issues with IPv6 routing rules.

**Comment by tarek-zy** [comment]
Superior support, and great enhancements.. I'm very impressed!!! Thank you very much!

I just updated to beta 3 successfully. I immediately noticed the creative change in "System Information" section, where it reports the IP Version with a note for the incompatibility I have! Although, I would like to see the word "Binary" or "Tool" besides the IP word there.

So, this beta now is initially working fine for my RT-AC68U. One, no IP binary restriction. Two, it uses the more recent IP binary version. Three, no OpenVPN limited clients bug. Well done!

I'll make a clean boot within some time and make sure that rule list is almost empty. Then I'll let it work as usual for several hours (depending on my next free time), then finally will report back to you with my findings after executing "ip rule list"

**Comment by tarek-zy** [comment]
After about 1 hour of testing as I'm writing now, I still got no rules at all displayed when using the command "ip rule list".

Although, the domains I have routed through OpenVPN Client 1 are working perfectly, and all other domains are routed normally via WAN! Would you please inform me how to test the new behavior on my router, so that I provide proper feedback the next update from me.

**Comment by Ranger802004** [comment]
Send me some of the logs, there would have to be some sort of rules in ip rule list or ip -6 rule list for things to work properly.

**Comment by tarek-zy** [comment]
Latest syslog-ng messages:
```
Oct 10 04:00:01 ATR domain_vpn_routing: Debug - IPv6 Service: disabled
Oct 10 04:00:03 ATR domain_vpn_routing: Test IP Version - Testing IP Version: 4.4.0
Oct 10 04:00:03 ATR domain_vpn_routing: Test IP Version - Domain VPN Routing may have compatibility issues with IP Version: 4.4.0
Oct 10 04:00:03 ATR domain_vpn_routing: Debug - Checking for missing global configuration options
Oct 10 04:00:04 ATR domain_vpn_routing: Debug - Reading /jffs/configs/domain_vpn_routing/global.conf
Oct 10 04:00:04 ATR domain_vpn_routing: Debug - Reading /jffs/configs/domain_vpn_routing/global.conf
Oct 10 04:00:04 ATR domain_vpn_routing: Debug - Checking Alias in /jffs/configs/profile.add
Oct 10 04:00:04 ATR domain_vpn_routing: Debug - Checking Alias in /jffs/configs/profile.add
Oct 10 04:00:04 ATR domain_vpn_routing: Debug - System Uptime: 10152 Seconds
Oct 10 04:00:04 ATR domain_vpn_routing: Debug - Boot Delay Timer: 0 Seconds
Oct 10 04:00:04 ATR domain_vpn_routing: Debug - Setting Process Priority to 0
Oct 10 04:00:04 ATR domain_vpn_routing: Query Policy - Set Process Priority to 0
Oct 10 04:00:04 ATR domain_vpn_routing: Debug - Setting Process Priority to 0
Oct 10 04:00:04 ATR domain_vpn_routing: Restore Policy - Set Process Priority to 0
Oct 10 04:00:04 ATR domain_vpn_routing: Debug - Routing Director Interface: ovpnc1
Oct 10 04:00:05 ATR domain_vpn_routing: Debug - DNS Director Interface: ovpnc1
Oct 10 04:00:15 ATR domain_vpn_routing: Query Policy - Updating Policy: ATR
Oct 10 04:00:15 ATR domain_vpn_routing: Query Policy - Updated Policy: ATR
Oct 10 04:00:16 ATR domain_vpn_routing: Debug - Routing Director Interface: ovpnc1
Oct 10 04:00:22 ATR domain_vpn_routing: Query Policy - Saving IPv4 IPSET for ATR
Oct 10 04:00:22 ATR domain_vpn_routing: Query Policy - Save IPv4 IPSET for ATR
Oct 10 04:00:22 ATR domain_vpn_routing: Debug - Checking for Lock File: /var/lock/domain_vpn_routing.lock
Oct 10 04:00:22 ATR domain_vpn_routing: Cleanup - Deleting /var/lock/domain_vpn_routing.lock
Oct 10 04:00:22 ATR domain_vpn_routing: Cleanup - Deleted /var/lock/domain_vpn_routing.lock
```

Latest ip rule list
```
0:      from all lookup local 
1000:   from all fwmark 0x1000/0xf000 lookup 111 
32766:  from all lookup main 
32767:  from all lookup default
```

**Comment by Ranger802004** [comment]
The 2nd rule in the list is your mark rule for the traffic assigned to your ovpn client 1 interface.  Table 111 is ovpnc1.

**Comment by tarek-zy** [comment]
I'm sorry as I didn't realize that these four lines are all what is supposed to be output from the command. Before your recent enhancement to workaround the old IP binary issue, I used to have hundreds of duplicate entries containing so many data like the following:
```
0:      from all lookup local 
1000:   from all fwmark 0x1000/0xf000 lookup 111 
1000:   from all fwmark 0x1000/0xf000 lookup 111 
1000:   from all to 104.16.208.203 lookup 111 
1000:   from all to 104.19.159.190 lookup 111 
1000:   from all to 185.199.108.133 lookup 111 
1000:   from all to 185.199.109.133 lookup 111 
1000:   from all to 185.199.110.133 lookup 111 
1000:   from all to 185.199.111.133 lookup 111 
1000:   from all fwmark 0x1000/0xf000 lookup 111 
1000:   from all fwmark 0x1000/0xf000 lookup 111 
1000:   from all to 104.16.208.203 lookup 111 
1000:   from all to 104.19.159.190 lookup 111 
1000:   from all to 185.199.108.133 lookup 111 
1000:   from all to 185.199.109.133 lookup 111 
1000:   from all to 185.199.110.133 lookup 111 
1000:   from all to 185.199.111.133 lookup 111 
1000:   from all fwmark 0x1000/0xf000 lookup 111 
1000:   from all fwmark 0x1000/0xf000 lookup 111 
1000:   from all to 104.16.208.203 lookup 111 
1000:   from all to 104.19.159.190 lookup 111 
1000:   from all to 185.199.108.133 lookup 111 
1000:   from all to 185.199.109.133 lookup 111 
1000:   from all to 185.199.110.133 lookup 111 
1000:   from all to 185.199.111.133 lookup 111 
32766:  from all lookup main 
32767:  from all lookup default
```

Things are working great so far! And I guess I'll very soon upgrade my other router (DSL-AC68U) to the beta version too

**Comment by Ranger802004** [comment]
Yep, all of those are unnecessary, you only need 1 IP rule per interface for IPv4 and 1 IP rule for IPv6 per interface.  The traffic is tagged using IPTables and IPSets and for your OVPN Client 1 it is being tagged with the default FWMark of 0x1000 with a mask of 0xf000 and that is how the traffic is being properly routed.

**Comment by tarek-zy** [comment]
Yesterday when I sent you my last update, I made sure that everything is working normally then went to sleep. Today, I didn't have free time until now, I just logged into my router to check out my logs.

Not so surprised, I didn't find any log records from your script since almost 20 hours, while I have it running every 30 minutes, and its cron job record is there. The catch is that I did some changes yesterday to my syslog-ng setup, because I have a strange issue recently preventing it from shutting down gracefully before almost every reboot of the router, and finally I figured out that I'm missing logs from other filters too.

Eventually, I went right away to check that the routing is working fine, and made a manual query from the main menu which was done successfully, so everything is working great!!!! I'm going now to upgrade my DSL router to the latest beta version of DomainVPNRouting, then make more thorough debugging for syslog-ng.

**Comment by tarek-zy** [comment]
This will be my last update regarding this issue, since it was totally solved, thankfully! Thus, I would ask you to please close this issue if you need no further follow ups on this issue.

Firstly, I wanted to confirm that DomainVPNRouting is working perfectly for me now at beta 3, as I let it work since Oct 11 12:30 local time, till now Oct 14 07:30, without any issues at all. I might open another issue later regarding suspected repeated log entries, and a suggested enhancement that could be a great addition to the script.

Regarding the logging issue I reported in my last post. After thorough investigation, I can confirm there's a serious issue with syslog-ng that wasn't present before Merlin 386.12_0, and I've found a similar issue in the SNBForums that I will participte in very soon, to try to find a solution for everyone running the same setup, as a new contribution from me to the community.
So, nothing related to DomainVPNRouting.

Best Wishes Ranger!

**Comment by Ranger802004** [comment]
v3.0.0 has been published to the production channel
