### ISSUE TITLE
Excessive WAN Failovers

### ISSUE THREAD

**Issue by routersecskisthedude** [Ranger802004/asusmerlin#37]
I have been experiencing excessive WAN failovers. Probably 20-30 per day. 
[wan-failover-2024-09-02-11.02.00-EDT.log](https://github.com/user-attachments/files/17370881/wan-failover-2024-09-02-11.02.00-EDT.log)

**Comment by Ranger802004** [comment]
I am not sure why your issue wasn't populated for me until now.  Can you capture the same data with debug logging enabled?

**Comment by Ranger802004** [comment]
Closing issue due to no response.

**Comment by routersecskisthedude** [comment]
Here are updated logs: 
[wan_failover_logs.txt](https://github.com/user-attachments/files/18132865/wan_failover_logs.txt)
