### ISSUE TITLE
DomainVPNRouting Triggers Suggestion: one-liner cron & query with delay

### ISSUE THREAD

**Issue by tarek-zy** [Ranger802004/asusmerlin#38]
Hi,

In my setup, and as I have one of the worst internet connections on Earth, with very frequent issues and disconnections. And while having the bugs that were recently fixed for my router models, I came up with a creative edit for the way the script is triggered during normal router operation.

A one line command that does both the "cron" and "querypolicy all" with some delay (40 seconds, inspired by script WICENS) until the connection is deemed "reliable" to trigger DomainVPNRouting to do its magic.

wan-event trigger:
```
if [ "$2" = "connected" ] then { ( sleep 40 && sh /jffs/scripts/domain_vpn_routing.sh cron ; sh /jffs/scripts/domain_vpn_routing.sh querypolicy all ) & }; fi # domain_vpn_routing`
```

openvpn-event trigger:
```
( sleep 40 && sh /jffs/scripts/domain_vpn_routing.sh cron ; sh /jffs/scripts/domain_vpn_routing.sh querypolicy all ) & # domain_vpn_routing
```

Please note that I specified to trigger the script on wan "connected" status only, as my routers send too many wan events while booting, or during re-connections, which means too many useless calls. Again, this is inspired by some other AMTM scripts I'm using in my setup. I can't remember if the installation process by default puts any more triggers in the "scripts" folder other than "wgclient-start", but I deleted all other triggers in my setup.

Thank you again for your great script! I LOVE IT!

**Comment by tarek-zy** [comment]
Here's another suggestion, instead of creating another GitHub issue for a suggestion...

You'll find attached my DomainVPNRouting log file for the last 18 hours straight. I converted the log text to a formatted data table in an Excel spreadsheet to enable data analysis and much better visual overview. I've came up with some ideas that I would like to suggest for the way the script generates log messages:

1- Since there's a single process priority configured for the script, why not merging the four log messages into two?
2- I don't know if it's a malfunction on my router model specifically, but why "reading global.conf" and "checking profile.add" messages are logged twice?
3- Are there anything I'm missing why the routing process is logged over three messages?
4- I guess checking and deleting the lock file could be merged in one log message, then informing whether it's deleted or not found in the very next log message.

Kindly,
Tarek

[DomainVPNRouting LOG.xlsx](https://github.com/user-attachments/files/17404523/DomainVPNRouting.LOG.xlsx)

**Comment by Ranger802004** [comment]
You have debug logging enabled, that's why you are seeing excessive logging, turn the logging level down on your router in the GUI from debug under System Log.

**Comment by Ranger802004** [comment]
I don't think adding timers in the wan-event, openvpn event, wg event scripts is a solution for that problem.  It is possible to monitor the WANs in NVRAM to get the state of them to see if they are connected, etc.  I do this extensively in the WAN Failover script.  I can look into adding some checks for that to delay or wait for processing domains/ASN in the policies for WAN states being connected.

**Comment by tarek-zy** [comment]
> You have debug logging enabled, that's why you are seeing excessive logging, turn the logging level down on your router in the GUI from debug under System Log.

Yeah, I am absolutely aware of this. I was filtering all messages from DVR through syslog-ng to a separate log file, I was literally suggesting for the logging at all levels.



> I can look into adding some checks for that to delay or wait for processing domains/ASN in the policies for WAN states being connected.

Yeah, this could be a good solution if you mean without enabling NVRAM checks in DVR's config. However, I still prefer doing the checks inside the *-event scripts to avoid calling DVR at all when it's not needed. Though, with your great scripting skills, I think you handle every aspect very well!

Good luck!

**Comment by tarek-zy** [comment]
Here's a quick insight at how many wan events my DSL-AC68U throws in a **single** wan disconnection:

```
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/service-event (args: restart dslwan_if)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 101 stopping)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 101 stopped)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 102 stopping)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 102 stopped)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 103 stopping)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 103 stopped)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 104 stopping)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 104 stopped)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 105 stopping)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 105 stopped)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 106 stopping)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 106 stopped)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 107 stopping)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 107 stopped)
Oct 21 00:40:18 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 0 stopping)
Oct 21 00:40:18 ATR-DSL custom_script: Running openvpn-event
Oct 21 00:40:19 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 0 disconnected)
Oct 21 00:40:19 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 0 stopped)
Oct 21 00:40:20 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 0 stopped)
Oct 21 00:40:27 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 101 disabled)
Oct 21 00:40:27 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 102 disabled)
Oct 21 00:40:27 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 103 disabled)
Oct 21 00:40:27 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 104 disabled)
Oct 21 00:40:27 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 105 disabled)
Oct 21 00:40:27 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 106 disabled)
Oct 21 00:40:27 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 107 disabled)
Oct 21 00:40:27 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 0 init)
Oct 21 00:40:27 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 0 connecting)
Oct 21 00:40:27 ATR-DSL custom_script: Running /jffs/scripts/service-event (args: restart stubby)
Oct 21 00:40:39 ATR-DSL custom_script: Running /jffs/scripts/firewall-start (args: )
Oct 21 00:41:03 ATR-DSL custom_script: Running /jffs/scripts/wan-event (args: 0 connected)
Oct 21 00:41:03 ATR-DSL custom_script: Running /jffs/scripts/firewall-start (args: ppp0)
Oct 21 00:41:04 ATR-DSL custom_script: Running /jffs/scripts/service-event (args: start vpnclient1)
```

That's why I very much prefer putting the event filter in wan-event script, thus preventing all these useless calls to your script, or any other script at all. Though, please note that it's not the same number of calls in my RT-AC68U router, they're just a few like other models. That's why I wanted to demonstrate to you what's happening in a DSL router at least, and I hope now you totally get my purpose.

**Comment by tarek-zy** [comment]
For comparison, here are all log records for a single WAN disconnection on my RT-AC68U:

```
Oct 21 01:09:45 ATR custom_script: Running /jffs/scripts/service-event (args: restart wan_if)
Oct 21 01:09:45 ATR custom_script: Running /jffs/scripts/wan-event (args: 0 stopping)
Oct 21 01:09:45 ATR custom_script: Running openvpn-event
Oct 21 01:09:47 ATR custom_script: Running /jffs/scripts/wan-event (args: 0 disconnected)
Oct 21 01:09:47 ATR custom_script: Running /jffs/scripts/wan-event (args: 0 stopped)
Oct 21 01:09:47 ATR custom_script: Running /jffs/scripts/wan-event (args: 0 stopped)
Oct 21 01:09:47 ATR custom_script: Running /jffs/scripts/wan-event (args: 0 init)
Oct 21 01:09:47 ATR custom_script: Running /jffs/scripts/wan-event (args: 0 connecting)
Oct 21 01:09:47 ATR custom_script: Running /jffs/scripts/wan-event (args: 0 disconnected)
Oct 21 01:09:47 ATR custom_script: Running /jffs/scripts/wan-event (args: 0 stopped)
Oct 21 01:09:47 ATR custom_script: Running /jffs/scripts/wan-event (args: 0 connected)
Oct 21 01:09:48 ATR custom_script: Running /jffs/scripts/firewall-start (args: eth0)
Oct 21 01:09:48 ATR custom_script: Running /jffs/scripts/service-event (args: start vpnclient1)
```
