### ISSUE TITLE
Wildcard not working

### ISSUE THREAD

**Issue by Qilbys** [Ranger802004/asusmerlin#39]
Hello!

First of all, thank you for developing this!
I installed the latest stable version (v3.0.0) but can't get wildcards to work.
I want all my traffic targeting dofus.com and Ankama.com to go through wan interface.
To do so, I created a policy and added the following domains: dofus.com, ankama.com, *.ankama.com
Then I ran querypolicy.
However, traffic is still going through the VPN connection and not the wan interface as expected.
Adding auth.ankama.com allowed me to go a little bit further but it was not enough as I received an alert email saying ankama blocked the authentication using my VPN IP. 
There is a lot of subdomains to Ankama.com and don't want to add all of them manually...

Here are some iptable information for troubleshooting:
```
#iptables -t mangle -nvL PREROUTING
Chain PREROUTING (policy ACCEPT 104K packets, 35M bytes)
 pkts bytes target     prot opt in     out     source               destination         
  17M   42G MARK       all  --  wgc1   *       0.0.0.0/0            0.0.0.0/0            MARK or 0x1
   26  3614 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set DVR-dofus-v4 dst MARK xset 0x8000/0xf000

# iptables -t mangle -nvL POSTROUTING
Chain POSTROUTING (policy ACCEPT 94332 packets, 26M bytes)
 pkts bytes target     prot opt in     out     source               destination         
  12M  710M MARK       all  --  *      wgc1    0.0.0.0/0            0.0.0.0/0            MARK or 0x1
   26  3614 MARK       all  --  *      eth4    0.0.0.0/0            0.0.0.0/0            match-set DVR-dofus-v4 dst MARK xset 0x8000/0xf000

# ip rule list
0:      from all lookup local
150:    from all fwmark 0x8000/0xf000 lookup main
11210:  from all lookup wgc1
32766:  from all lookup main
32767:  from all lookup default

```

If you need more, let me know!

Regards.

Qilbys

**Comment by Ranger802004** [comment]
The wildcard domains are passively picked up from DNS Logging, as documented make sure that is enabled to use wildcard domains.

**Comment by Qilbys** [comment]
Thank you for your answer!
I already did: 
`# cat /jffs/configs/dnsmasq.conf.add 
log-queries`


![image](https://github.com/user-attachments/assets/8a84f0ab-edd1-40ad-9eb1-185aa7683063)

**Comment by Qilbys** [comment]
Do you know how to specify it ? I can't find the settings for this...
Thank you!

**Comment by Qilbys** [comment]
I found the issue. I installed a nextdns script on my Mac as a result, router was not used as default dns.
Closing issue.
