### ISSUE TITLE
NEWASNINTERFACE: parameter not set

### ISSUE THREAD

**Issue by dorner365** [Ranger802004/asusmerlin#41]
Error on version 3.01 Beta - Option 15 - Edit policy:

> Select the Policy You Want to Edit: 10
Press any key to continue to edit Policy: ssp
Interfaces:
ovpnc1
ovpnc2
ovpnc3
ovpnc4
ovpnc5
ovpns1
wgc2
wgc3
wgc4
wgc5
wan
Current Interface: wgc2
Select an Interface for this Policy: ovpnc2
Enable verbose logging for this policy? ***Enter Y for Yes or N for No*** n
Enable Private IP Addresses for this policy? ***Enter Y for Yes or N for No*** n
Enable adding CNAMES for this policy? ***Enter Y for Yes or N for No*** y
domain_vpn_routing: Edit Policy - Modified ssp in /jffs/configs/domain_vpn_routing/domain_vpn_routing.conf
**/jffs/scripts/domain_vpn_routing.sh: line 40: NEWASNINTERFACE: parameter not set**

NOTES: 
1. None of the policies are configured for ASNs
2. /jffs/configs/domain_vpn_routing/domain_vpn_routing.conf gets updated with the new interface
3. `iptables -nvL PREROUTING -t mangle --line` shows the old interface: `DVR-ssp-v4 dst MARK xset 0xb000/0xf000`

**Comment by Ranger802004** [comment]
I have identified the issue and will have it resolved on the next update.
