### ISSUE TITLE
Feature request: option to temporarily disable Domain VPN Routing

### ISSUE THREAD

**Issue by dorner365** [Ranger802004/asusmerlin#42]
That would be helpful for troubleshooting (un)related issues.

**Comment by Ranger802004** [comment]
In what aspect are you trying to disable Domain VPN Routing? Are you wanting to disable the querying aspect, restoration, etc?

**Comment by dorner365** [comment]
Two ways (not mutually exclusive)
 1. menu option to temporarily disable it - current option 12 'kill' + delete cron job + delete all rules + remove the statements from different places in /jffs/scripts such that policies are not being rebuilt etc. And another option to restart the script as before.
 2. Upon option 5 'uninstall' provide the option to backup all settings and files before deletion. Upon installing the script check if a backup exists and provide the option to restore the last backup or install clean.

**Comment by dorner365** [comment]
1. As long as any unrelated event call (i.e. wgclient-start, wan-event etc) would not recreate / re-enable the policies that's fine. 
2. Looking forward to that :).

**Comment by Ranger802004** [comment]
1. Yes the event calls wouldn't matter, they'll call the script and the script would see it is in disabled state and do nothing other than check that the rules are deleted to ensure routing is not being done by Domain VPN Routing.

**Comment by dorner365** [comment]
That would be it.... thank you!

**Comment by Ranger802004** [comment]
These options have been included in v3.0.2-beta1 that is now released on the Beta update channel.

**Comment by dorner365** [comment]
I appreciate your time and effort to make your good script do more...
Here are some observations 'from the field':
1a. Removing the fwmark ip rules gets the job done. However, it's still a taste of weirdness looking at the fact that the packet routing goes on on empty... meaning the iptables rules are still in place.
1b. While the script is disabled, it would be a nice touch to display a note to that effect on the main menu.
2.  The uninstall process creates a backup if so requested. However, the restore process looks like this:
'Do you want to restore configuration of Domain VPN Routing? ***Enter Y for Yes or N for No*** > y
domain_vpn_routing: Install - Restoring configuration from /jffs/configs/domain_vpn_routing.tar.gz
domain_vpn_routing: Install - Restored configuration from /jffs/configs/domain_vpn_routing.tar.gz
domain_vpn_routing: Install - Creating /jffs/configs/domain_vpn_routing/asn.conf
domain_vpn_routing: Install - /jffs/configs/domain_vpn_routing/asn.conf created
domain_vpn_routing: Install - Adding domain_vpn_routing cron job to wan-event
domain_vpn_routing: Install - domain_vpn_routing cron job added to wan-event
domain_vpn_routing: Install - domain_vpn_routing added to wan-event
domain_vpn_routing: Install - Adding domain_vpn_routing cron job to openvpn-event
domain_vpn_routing: Install - domain_vpn_routing cron job added to openvpn-event
domain_vpn_routing: Install - Adding domain_vpn_routing to openvpn-event
domain_vpn_routing: Install - domain_vpn_routing added to openvpn-event
domain_vpn_routing: Install - Adding domain_vpn_routing Cron Job to wgclient-start
domain_vpn_routing: Install - domain_vpn_routing Cron Job added to wgclient-start
domain_vpn_routing: Install - Adding domain_vpn_routing Query Policy All to wgclient-start
domain_vpn_routing: Install - domain_vpn_routing Query Policy All added to wgclient-start
/jffs/scripts/domain_vpn_routing.sh: line 6794: CHECKINTERVAL: parameter not set`

It would be nice to run option 11 (Restore policy) - all, after restore such that the iptables rules and ipsets are restored too.

**Comment by Ranger802004** [comment]
I see why that would be an issue, it needs to load the config file after restoring the configuration.  I'll update the logic for that during the install, simply exit the script and reopen in the meantime and it should be fine.

**Comment by Ranger802004** [comment]
The IPTables rules for enabling/disabling would be a little bit more complicated as they would require a lot more looping to process through each policy since the IPSets are configured on those.  The rules being there should be benign since the IP rules are not routing the traffic.

**Comment by Ranger802004** [comment]
v3.0.2-beta2 has been released to the beta channel, it includes updated logic for the configuration restore during install as well as executing restorepolicy all right after install is complete if restoring a configuration.

**Comment by Ranger802004** [comment]
v3.0.2 has been released to resolve this issue.  Open a new GitHub issue for any additional issues or feature requests.
