### ISSUE TITLE
WAN Failover not working as intended ! Wan 0 is sticking on HotStandby instead of switching

### ISSUE THREAD

**Issue by computersteve** [Ranger802004/asusmerlin#44]
My Wan 0 isn't switching back and instead when internet is restored it says Hotstandby: I can manually fix this by going into the script and running Manually switch Primary WAN. However I thought the purpose of the script is to do this automatically. 

Here are the script status and configurations: 

WAN Failover Status:
Model: GT-AX11000_PRO
Host Name: 
Firmware Version: 388.8
JFFS Scripts: Enabled
Dual WAN: Enabled
Mode: Failover Mode
WAN Failover Version: v2.1.2
Status: Failover Monitoring
Last Update: Wed Oct 23 11:14:43 EDT 2024

WAN0:
Status: Connected
Primary: No
IP Address: 
Gateway: 
Interface: eth0
MAC Address: 
WAN0 Target: 8.8.8.8
Packet Loss: 100%
WAN Failover Status:
Model: GT-AX11000_PRO
Host Name: 
Firmware Version: 388.8
JFFS Scripts: Enabled
Dual WAN: Enabled
Mode: Failover Mode
WAN Failover Version: v2.1.2
Status: Failover Monitoring
Last Update: Wed Oct 23 11:15:14 EDT 2024

WAN0:
Status: Connected
Primary: No
IP Address: 
Gateway: 
Interface: eth0
MAC Address: 
WAN0 Target: 8.8.8.8
Packet Loss: 100%
Ping Time: N/A
WAN Failover Status:
Model: GT-AX11000_PRO
Host Name: home
Firmware Version: 388.8
JFFS Scripts: Enabled
Dual WAN: Enabled
Mode: Failover Mode
WAN Failover Version: v2.1.2
Status: Failover Monitoring
Last Update: Wed Oct 23 11:15:27 EDT 2024

WAN0:
Status: Connected
Primary: No
IP Address: 148.74.
Gateway: 148.74.
Interface: eth0
MAC Address: 
WAN0 Target: 8.8.8.8
Packet Loss: 100%
WAN Failover Status:
Model: GT-AX11000_PRO
Host Name: home
Firmware Version: 388.8
JFFS Scripts: Enabled
Dual WAN: Enabled
Mode: Failover Mode
WAN Failover Version: v2.1.2
Status: Failover Monitoring
Last Update: Wed Oct 23 11:15:58 EDT 2024

WAN0:
Status: Connected
Primary: No
IP Address: 
Gateway: 
Interface: eth0
MAC Address: 
WAN0 Target: 8.8.8.8
Packet Loss: 100%
Ping Time: N/A

# WAN Failover for ASUS Routers using ASUS Merlin Firmware
# Author: Ranger802004 - https://github.com/Ranger802004/asusmerlin/
# Date: 07/25/2024
# Version: v2.1.2

  Information:
  (1)  status      Status Information about WAN Failover
  (2)  readme      View WAN Failover Readme

  Installation/Configuration:
  (3)  install     Install WAN Failover
  (4)  uninstall   Uninstall WAN Failover
  (5)  config      Configuration of WAN Failover
  (6)  update      Check for updates for WAN Failover

  Operations:
  (7)  run         Schedule WAN Failover to run via Cron Job
  (8)  manual      Execute WAN Failover from Interactive Console
  (9)  initiate    Execute WAN Failover to only create Routing Table Rules, IP Rules, and IPTable Rules
  (10) monitor     Monitor System Log for WAN Failover Events
  (11) capture     Capture System Log for WAN Failover Events
  (12) restart     Restart WAN Failover
  (13) kill        Kill all instances of WAN Failover and unschedule Cron Jobs
  (14) switchwan   Manually switch Primary WAN.  ***Failover Mode Only***

  (e)  exit        Exit WAN Failover Menu

# WAN Failover for ASUS Routers using ASUS Merlin Firmware
# Author: Ranger802004 - https://github.com/Ranger802004/asusmerlin/
# Date: 07/25/2024
# Version: v2.1.2

  Information:
  (1)  status      Status Information about WAN Failover

  Failover Monitoring Settings:
  (1)  Configure WAN0 Target           WAN0 Target: 8.8.8.8
  (2)  Configure WAN1 Target           WAN1 Target: 8.8.4.4
  (3)  Configure Ping Count            Ping Count: 3
  (4)  Configure Ping Timeout          Ping Timeout: 1
  (5)  Configure Ping Time Min         Ping Time Minimum: 40ms
  (6)  Configure Ping Time Max         Ping Time Maximum: 80ms

  QoS Settings:
  (7)  Configure WAN0 QoS              WAN0 QoS: Disabled
  (8)  Configure WAN1 QoS              WAN1 QoS: Disabled

  Optional Settings:
  (9)  Configure Packet Loss Logging   Packet Loss Logging: Enabled
  (10) Configure Boot Delay Timer      Boot Delay Timer: 0 Seconds
  (11) Configure Email Notifications   Email Notifications: Enabled
  (12) Configure WAN0 Packet Size      WAN0 Packet Size: 56 Bytes
  (13) Configure WAN1 Packet Size      WAN1 Packet Size: 56 Bytes
  (14) Configure NVRAM Checks          NVRAM Checks: Disabled
  (15) Configure Dev Mode              Dev Mode: Disabled
  (16) Configure Custom Log Path       Custom Log Path: Disabled
  (17) Configure WAN0 Web GUI          WAN0 Web GUI IP Address: Disabled
  (18) Configure WAN1 Web GUI          WAN1 Web GUI IP Address: Disabled

**Comment by Ranger802004** [comment]
The status output looks like it is missing data and copy paste of redundant data.  Your WAN0 is reporting as 100% packet loss, that's why it hasn't switched.  I would need debug logs to diagnose this further.  Yes the script will automatically switch back to WAN0 when it is restored.

**Comment by computersteve** [comment]
How do I get debug logs ?

**Comment by Ranger802004** [comment]
Enable debug logging on your router in the GUI under System Logs, execute capture from WAN Failover menu and then repeat your failure scenario.  The logs will be collected in a temp file under /tmp, when you finish running capture it will prompt the name of the generated file.

**Comment by computersteve** [comment]
So I am unable to do it this way because every time I do it by doing it in this controlled way it works correclty... its everytime I leave the router a lone for a few days then randomly in like a week I will notice the router is on the secondary wan and it hasn't recovered to the primary wan instead it says Hot standby... Heres a log if it helps but it worked this time so I don't think its going to help.. It works every time I manually do it. 
[wan-failover-2024-10-24-23:12:39-EDT.log.zip](https://github.com/user-attachments/files/17515282/wan-failover-2024-10-24-23.12.39-EDT.log.zip)

**Comment by Ranger802004** [comment]
Do you have NVRAM checks enabled? If so enable it and let it run for a few days again.

**Comment by computersteve** [comment]
> Do you have NVRAM checks enabled? If not, enable it and let it run for a few days again.

No I do not have NVRAM checks enabled: -- 
Do you mean enable it, and then let the script just run normally correct? you don't mean execute a capture for a few days ???

**Comment by Ranger802004** [comment]
Yes, enable it and let the script run normally and see if that corrects the behavior you are seeing.

**Comment by Ranger802004** [comment]
Following up, have you had any issues since enabling NVRAM Checks?

**Comment by computersteve** [comment]
> Following up, have you had any issues since enabling NVRAM Checks?

I didn’t notice it in a while so far. I am still keeping an eye out on it.

**Comment by Ranger802004** [comment]
Following up with you on this issue.

**Comment by computersteve** [comment]
> Following up with you on this issue.

so far it seems good ! However.. I didn't loose my internet connection so I really can't tell you lol meaning its if it switches does it handle the switch properly..

**Comment by computersteve** [comment]
by the way I noticed this in the logs: 
Nov  5 15:44:59 wan-failover: NVRAM Check - ***NVRAM Check Failure Detected***
Nov  5 15:45:00 domain_vpn_routing: Debug - IPv6 Service: disabled
Nov  5 15:45:00 domain_vpn_routing: Test IP Version - Testing IP Version: 5.11.0
Nov  5 15:45:00 domain_vpn_routing: Test IP Version - IP Version: 5.11.0 passed
Nov  5 15:45:00 domain_vpn_routing: Debug - Checking for missing global configuration options
Nov  5 15:45:00 domain_vpn_routing: Debug - Reading /jffs/configs/domain_vpn_routing/global.conf
Nov  5 15:45:00 domain_vpn_routing: Debug - Reading /jffs/configs/domain_vpn_routing/global.conf
Nov  5 15:45:00 domain_vpn_routing: Debug - Checking Alias in /jffs/configs/profile.add
Nov  5 15:45:00 domain_vpn_routing: Debug - Domain VPN Routing is Enabled
Nov  5 15:45:00 domain_vpn_routing: Debug - Checking Alias in /jffs/configs/profile.add
Nov  5 15:45:01 domain_vpn_routing: Debug - System Uptime: 189588 Seconds
Nov  5 15:45:01 domain_vpn_routing: Debug - Boot Delay Timer: 0 Seconds
Nov  5 15:45:01 domain_vpn_routing: Debug - Setting Process Priority to 0
Nov  5 15:45:01 domain_vpn_routing: Set Process Priority - Set Process Priority to 0
Nov  5 15:45:01 domain_vpn_routing: Debug - Domain VPN Routing is Enabled
Nov  5 15:45:01 domain_vpn_routing: Debug - System Uptime: 189588 Seconds
Nov  5 15:45:01 domain_vpn_routing: Debug - Boot Delay Timer: 0 Seconds
Nov  5 15:45:01 domain_vpn_routing: Debug - Setting Process Priority to 0
Nov  5 15:45:01 domain_vpn_routing: Set Process Priority - Set Process Priority to 0
Nov  5 15:45:01 domain_vpn_routing: Debug - Routing Director Interface: wan
Nov  5 15:45:01 domain_vpn_routing: Debug - Checking wan for Default Route in Routing Table main
Nov  5 15:45:01 domain_vpn_routing: Debug - Routing Director Interface: wan
Nov  5 15:45:01 domain_vpn_routing: Debug - Checking wan for Default Route in Routing Table main
Nov  5 15:45:01 domain_vpn_routing: Debug - Routing Director Interface: wan
Nov  5 15:45:01 domain_vpn_routing: Debug - Checking wan for Default Route in Routing Table main
Nov  5 15:45:01 domain_vpn_routing: Debug - Routing Director Interface: wan
Nov  5 15:45:01 domain_vpn_routing: Debug - Checking wan for Default Route in Routing Table main
Nov  5 15:45:01 domain_vpn_routing: Debug - Routing Director Interface: wan
Nov  5 15:45:01 domain_vpn_routing: Debug - Checking wan for Default Route in Routing Table main
Nov  5 15:45:01 domain_vpn_routing: Debug - DNS Director Interface: wan
Nov  5 15:45:01 domain_vpn_routing: Debug - Routing Director Interface: wan
Nov  5 15:45:02 domain_vpn_routing: Debug - Checking wan for Default Route in Routing Table main
Nov  5 15:45:03 domain_vpn_routing: Debug - DNS Director Interface: wan
Nov  5 15:45:03 domain_vpn_routing: Debug - Routing Director Interface: wan
Nov  5 15:45:03 domain_vpn_routing: Debug - Checking wan for Default Route in Routing Table main
Nov  5 15:45:07 domain_vpn_routing: Debug - DNS Director Interface: wan
Nov  5 15:45:07 domain_vpn_routing: Debug - Routing Director Interface: wan
Nov  5 15:45:07 domain_vpn_routing: Debug - Checking wan for Default Route in Routing Table main
Nov  5 15:45:07 domain_vpn_routing: Debug - DNS Director Interface: wan
Nov  5 15:45:08 domain_vpn_routing: Query Policy - Updating Policy: Hulu
Nov  5 15:45:08 domain_vpn_routing: Query Policy - Updated Policy: Hulu
Nov  5 15:45:08 domain_vpn_routing: Debug - Routing Director Interface: wan
Nov  5 15:45:08 domain_vpn_routing: Debug - Checking wan for Default Route in Routing Table main
Nov  5 15:45:10 ovpn-server1[39258]: Connection Attempt read UDPv4 [CMSG=8|EHOSTUNREACH]: No route to host (fd=9,code=113)
Nov  5 15:45:27 rc_service: watchdog 2694:notify_rc stop_aae
Nov  5 15:45:27 rc_service: watchdog 2694:notify_rc start_mastiff
Nov  5 15:45:27 rc_service: waitting "stop_aae" via watchdog ...
Nov  5 15:45:27 custom_script: Running /jffs/scripts/service-event-end (args: stop aae)
Nov  5 15:45:28 custom_script: Running /jffs/scripts/service-event-end (args: start mastiff)
Nov  5 15:45:28 Mastiff: init
Nov  5 15:45:58 rc_service: watchdog 2694:notify_rc stop_aae
Nov  5 15:45:58 rc_service: watchdog 2694:notify_rc start_mastiff
Nov  5 15:45:58 rc_service: waitting "stop_aae" via watchdog ...
Nov  5 15:45:58 custom_script: Running /jffs/scripts/service-event-end (args: stop aae)
Nov  5 15:45:59 custom_script: Running /jffs/scripts/service-event-end (args: start mastiff)
Nov  5 15:45:59 Mastiff: init
Nov  5 15:46:05 domain_vpn_routing: Query Policy - Saving IPv4 IPSET for Hulu
Nov  5 15:46:05 domain_vpn_routing: Query Policy - Save IPv4 IPSET for Hulu
Nov  5 15:46:05 domain_vpn_routing: Debug - DNS Director Interface: wan
Nov  5 15:46:05 domain_vpn_routing: Debug - Routing Director Interface: wan
Nov  5 15:46:05 domain_vpn_routing: Debug - Checking wan for Default Route in Routing Table main
Nov  5 15:46:07 domain_vpn_routing: Query Policy - Processing Time: 67 seconds
Nov  5 15:46:07 domain_vpn_routing: Debug - Domain VPN Routing is Enabled
Nov  5 15:46:07 domain_vpn_routing: Debug - Checking Alias in /jffs/configs/profile.add
Nov  5 15:46:07 domain_vpn_routing: Debug - System Uptime: 189654 Seconds
Nov  5 15:46:07 domain_vpn_routing: Debug - Boot Delay Timer: 0 Seconds
Nov  5 15:46:07 domain_vpn_routing: Debug - Setting Process Priority to 0
Nov  5 15:46:07 domain_vpn_routing: Set Process Priority - Set Process Priority to 0
Nov  5 15:46:07 domain_vpn_routing: Debug - Checking for Lock File: /var/lock/domain_vpn_routing.lock
Nov  5 15:46:07 domain_vpn_routing: Cleanup - Deleting /var/lock/domain_vpn_routing.lock
Nov  5 15:46:07 domain_vpn_routing: Cleanup - Deleted /var/lock/domain_vpn_routing.lock
Nov  5 15:46:29 rc_service: watchdog 2694:notify_rc stop_aae
Nov  5 15:46:29 rc_service: watchdog 2694:notify_rc start_mastiff
Nov  5 15:46:29 rc_service: waitting "stop_aae" via watchdog ...
Nov  5 15:46:29 custom_script: Running /jffs/scripts/service-event-end (args: stop aae)
Nov  5 15:46:30 custom_script: Running /jffs/scripts/service-event-end (args: start mastiff)
Nov  5 15:46:30 Mastiff: init
Nov  5 15:47:00 rc_service: watchdog 2694:notify_rc stop_aae
Nov  5 15:47:00 rc_service: watchdog 2694:notify_rc start_mastiff
Nov  5 15:47:00 rc_service: waitting "stop_aae" via watchdog ...
Nov  5 15:47:00 custom_script: Running /jffs/scripts/service-event-end (args: stop aae)
Nov  5 15:47:01 custom_script: Running /jffs/scripts/service-event-end (args: start mastiff)
Nov  5 15:47:01 Mastiff: init
Nov  5 15:47:31 rc_service: watchdog 2694:notify_rc stop_aae
Nov  5 15:47:31 rc_service: watchdog 2694:notify_rc start_mastiff
Nov  5 15:47:31 rc_service: waitting "stop_aae" via watchdog ...
Nov  5 15:47:31 custom_script: Running /jffs/scripts/service-event-end (args: stop aae)
Nov  5 15:47:32 custom_script: Running /jffs/scripts/service-event-end (args: start mastiff)
Nov  5 15:47:32 Mastiff: init

**Comment by Ranger802004** [comment]
That is normal with NVRAM checking enabled, that checks for stuck processes that can halt the script execution and kill them to prevent that from happening.  It is a proprietary workaround feature I built into my scripts for Reliability.  It will also cause the script to go back and reattempt to capture the NVRAM value that was not successful due to the stuck process. If NVRAM Checks were not enabled it would have caused the script to halt and be stuck until the NVRAM process was killed.
