### ISSUE TITLE
[Feature Request] More customizable notification options for WAN Failover

### ISSUE THREAD

**Issue by mingaldrichgan** [Ranger802004/asusmerlin#45]
Thanks for your work! I was wondering if you might consider adding more customizable notification options for WAN Failover? For example, running a custom shell command or calling a custom REST API URL?

Specifically for me:
* I have a Netgear LTE modem as my Secondary WAN. Thanks to WAN Failover, I am able to keep it in Hot-Standby so that I can always access the web interface, which also exposes a REST API that I use to send SMS notifications from Home Assistant via the [Netgear LTE integration](https://www.home-assistant.io/integrations/netgear_lte/) (which uses [the `eternalegypt` Python library](https://github.com/amelchio/eternalegypt). I would love to be able to set up SMS notifications from WAN Failover as well.
* I currently have AMTM email notifications sent to Gmail via [Brevo SMTP](https://www.brevo.com/landing/smtp/). Starting around the end of June, the emails started including inline `<br />` tags where there used to be proper line breaks. I don't know whether this change originated from WAN Failover, Brevo, or Gmail, but it would be great to have an option to turn off HTML formatting.
* I've been dealing with a flaky Primary WAN connection this past month, and noticed that whenever AMTM email notifications fail (which seems to happen a lot when there are many WAN Failover events within a short timespan), falling back to AIProtection (as seen in system log entries like the ones below), I get an empty Gmail email from myself, with nothing in the subject nor body. I assume this is an AIProtection issue, but this is another reason I would like to use SMS for notifications instead.
```
Oct 24 08:26:45 wan-failover: Email Notification - Email Notification via amtm Failed
Oct 24 08:26:54 wan-failover: Email Notification - Email Notification via AIProtection Alerts Sent
```

**Comment by Ranger802004** [comment]
Do you have a Gmail account you could test with and see if you have the same results?

**Comment by Ranger802004** [comment]
Closing issue due to no response.

**Comment by mingaldrichgan** [comment]
Hi, sorry I didn't see your question earlier. Yes, I am indeed using a Gmail account. If I'm misunderstanding your question, could you please clarify?

But I consider this more of a feature request—regardless of having AIProtection Alerts emails (which I've read from other reports doesn't work very well anyway) as a fallback, it would be great to be able to use other mechanisms for notifications. Just thought it was worth suggesting. :-)

**Comment by Ranger802004** [comment]
WAN Failover just uses what is configured in amtm for alerts and AIProtection Alerts as back up if configured.  There's no proprietary alert configuration with WAN Failover other than the alerts being generated themselves.
