### ISSUE TITLE
Bug in update function or Domain Routing script? 

### ISSUE THREAD

**Issue by computersteve** [Ranger802004/asusmerlin#47]
So i'm not sure if this is related to whats happening with the other script Wan Failover but Domain vpn routing script is now stating everytime I try to update it:
domain_vpn_routing: Restart - ***domain_vpn_routing is not running*** No Process ID Detected
& it doesn't update .... It eventually updates but I have to run the updater multiple times for it to work... I don't have NVRAM Checks enabled on this scrip I only enabled it on Wailfailover script as you instructed... Does it also need to be enabled on this script as well?

**Comment by computersteve** [comment]
This is the error::: 
domain_vpn_routing: Restart - ***domain_vpn_routing is not running*** No Process ID Detected
***domain_vpn_routing is not running*** No Process ID Detected

**Comment by Ranger802004** [comment]
The no process ID error is benign, it's just trying to kill any running processes after an update.  You have to Ctl + C out of the script all together and re-execute for it to show the proper version being installed.  This is because it's already loaded in memory in your session when you have the menu up.

**Comment by Ranger802004** [comment]
Enabling NVRAM checks could be needed, it is to resolve a lock up issue with the ASUS WRT routers when calling nvram values, it is a proprietary workaround solution I came up with for my scripts to prevent it but it slows down execution some but prevents the lock ups.

**Comment by Ranger802004** [comment]
I received an email you responded to this on the AdGuardHome issue thread but I don't see the comment, I implemented a fix for on v3.0.2-beta2 but the update function won't work until you update from this version to the next.

**Comment by Ranger802004** [comment]
v3.0.2 has been released to resolve this issue.  Open a new GitHub issue for any additional issues or feature requests.
