### ISSUE TITLE
[Suggestion] "No ASNs Detected" log message at error level in syslog-ng !

### ISSUE THREAD

**Issue by tarek-zy** [Ranger802004/asusmerlin#48]
Hi,

I'm one of those who pay a lot of attention to all the logs they have in their systems and organize them, and I really appreciate the total care that has been put into DVR for organizing all of its output log messages.

After participating in a recent bug fix and enhancement here, I went back to my default method of eliminating log messages to a specific degree. Specifically, I returned to filtering DVR messages to only show error level log messages and higher. Of course I filtered out the "compatibility mode error" that I'll always have on my routers, so it doesn't get me used to seeing errors that cannot be fixed.

Now that the new ASN feature has been introduced in the latest versions of DVR, I have this log message
`Query ASN - ***No ASNs Detected***`
getting logged with every run of the script (30 minutes), filling my logs with not useful messages, to me at least!

However, instead of filtering it out, I thought of suggesting a workaround for people who don't and won't use this feature, and thought that it should not appear at error level. Any other creative workaround would be much appreciated.

Kindly,
Tarek

**Comment by Ranger802004** [comment]
It will be addressed on the next beta release.

**Comment by Ranger802004** [comment]
This is resolved in v3.0.2-beta2 which is now released on the beta channel.

**Comment by tarek-zy** [comment]
Thanks! I just started testing, and will give you feedback within 48 hours.

**Comment by tarek-zy** [comment]
Everything is working great! And I really like the execution timer you added!
Thank you a lot, all the best!
