### ISSUE TITLE
Feature suggestion for next releases

### ISSUE THREAD

**Issue by ThePhoenix576** [Ranger802004/asusmerlin#5]
So as you know, sometimes when the main internet is down. It is not down completely. Sometimes it fails 5 secs of ping and then it goes through again and sometimes it fails again. When it does failover to the WAN1, it would be nice to have different fallback conditions. For example, to only fallback to the WAN0 if it manages to pass maybe an X amount of consecutive pings, or if the ping is lower than X ms etc. 

Thank you and great script !!

**Comment by Ranger802004** [comment]
Failback requires 0% packet loss (No packet loss from any pings set by the PINGCOUNT option) already.  There is a possibility for adding ping time as a failover / failback condition in a future release.
