### ISSUE TITLE
Only ASN

### ISSUE THREAD

**Issue by maghuro** [Ranger802004/asusmerlin#50]
I only have ASN configured. No policies.
When the cronjob runs, as I don't have any policy, it stops processing and don't update ASNs range of IPs

**Comment by Ranger802004** [comment]
I have identified the issue and actively working on a fix for this.

**Comment by Ranger802004** [comment]
v3.0.2-beta3 has been published which includes a fix for this issue.

Release Notes:
v3.0.2-beta3 - 11/02/2024
Enhancements:
- Added functionality to query the AdGuardHome log.  This can be enabled or disabled via the QUERYADGUARDHOMELOG configuration option.
- Created option to enable/disable Domain VPN Routing under configuration menu.
- During uninstallation, a prompt has been added to ask to back up the configuration.  When reinstalling Domain VPN Routing a backup file will be checked for existence and prompted to restore configuration.
- Removed log message regarding No ASNs being detected if queryasn function is being executed by querypolicy for all policies.
- Enhanced prompts in querypolicy mode.
- Added log message stating length of processing time for querypolicy function.
- Minor optimizations.

Fixes:
- Fixed script locking mechanism when executing querypolicy or queryasn from the UI menu.
- Fixed issue where ASNs were not queried by cron job if no domain policies were created.

**Comment by maghuro** [comment]
Working flawlessly, thanks!

A question - if a range of IPs is removed from a ASN, will it also be removed on the next Cron run?

**Comment by Ranger802004** [comment]
> Working flawlessly, thanks!
> 
> A question - if a range of IPs is removed from a ASN, will it also be removed on the next Cron run?

That's currently not in the logic however a reload / restart would resync the ASN from a fresh load of subnets.

**Comment by Ranger802004** [comment]
v3.0.2 has been released to resolve this issue.  Open a new GitHub issue for any additional issues or feature requests.
