### ISSUE TITLE
Script fails when syslog is used in dnsmasq.conf, i.e. log-facility=syslog.

### ISSUE THREAD

**Issue by CiViC321** [Ranger802004/asusmerlin#55]
I use syslog-ng and logrotate to manage my log files.  A syslog-ng log rule will write /opt/var/log/dnsmasq.log.

The script should ask, or assume, the log file path if syslog is used as log facility.

**Comment by Ranger802004** [comment]
Can you provide a copy of your dnsmasq config file as well as the log file?

**Comment by CiViC321** [comment]
Here are the files requested.

[domain_vpn_routing.log](https://github.com/user-attachments/files/17840586/domain_vpn_routing.log)
[dnsmasq.txt](https://github.com/user-attachments/files/17840591/dnsmasq.txt) (Renamed from conf to allow upload).

Thanks so much!!

**Comment by Ranger802004** [comment]
Sorry, I should have clarified better, I need a copy of the dnsmasq log file.  Also, is this optionally configured in syslog-ng? Where is the binary path of syslog-ng located when installed?

**Comment by Ranger802004** [comment]
Checking back with you for the additional data.

**Comment by CiViC321** [comment]
Apologies, I only saw now that that 
[logrotate.conf.txt](https://github.com/user-attachments/files/17954780/logrot
[dnsmasq.log.tar.xz.txt](https://github.com/user-attachments/files/17954807/dnsmasq.log.tar.xz.txt)
ate.conf.txt)
[syslog-ng.conf.txt](https://github.com/user-attachments/files/17954781/syslog-ng.conf.txt)
mail bounce because the log file was too large. 
[dnsmasq.txt](https://github.com/user-attachments/files/17954773/dnsmasq.txt)

Here are the additional files you requested.
[dnsmasq_1.txt](https://github.com/user-attachments/files/17954775/dnsmasq_1.txt)

I added the txt extension to all file to be able to upload them.

**Comment by Ranger802004** [comment]
So this is the stanza where your dnsmaq log location is defined, right?

destination d_dnsmasq { 
	file("/opt/var/log/dnsmasq.log");
};

**Comment by Ranger802004** [comment]
Where are these files located for syslog-ng? The config files specifically, I need the full paths.  Also what is the binary path when it is installed for syslog-ng?
