### ISSUE TITLE
Manually running switchwan not working

### ISSUE THREAD

**Issue by JonathanPowe** [Ranger802004/asusmerlin#6]
I have successfully installed wan-failover, and it appears to be working ok for most things. 
When I tried to manually switch from the Primary WAN to the Secondary WAN it looked like it ran successfully (no error messages displayed), however after it ran through the various processes the Primary WAN was still the one in use. 

I tested both options: running "wan-failover switchwan" and option 14 from the menu. Both appear to have the same results. 
 
Is there something that I have missed, or is this a big?

**Comment by Ranger802004** [comment]
Are you running WAN Failover failover monitoring? If so it will switch it back to WAN0 automatically if the link is testing as successful with no packet loss.

**Comment by Ranger802004** [comment]
Closing due to no response

**Comment by JonathanPowe** [comment]
Apologies for the delay in replying. I think what I was looking for was a way to instruct the router to swap which Internet connection was Primary / Secondary, and then to continue with the failover monitoring but with the opposite connection. 
(the reason was because the main internet connection had a temporary issue accessing certain services through it, so I wanted to switch to the backup connection whilst that issue was being resolved) 
 
I found a 2-step workaround though: 
Step 1: Using the router web GUI 'Dual Wan' page, change the dropdown boxes for "Primary" and "Secondary" to swap which one was assigned the main and backup Internet connections, click apply and wait for it to reboot 
_this results in the "Secondary" connection (with the Internet connection that previously was on "Primary") showing as "Connected"._ 
Step 2: Using the command line, run "wan-failover switchwan" or option 14, and wait for it to complete 
_this results in the new "Primary" connection (the backup Internet connection) showing as "Connected"_ 
  
Changing back to the main Internet connection required only to change the dropdown boxes for "Primary" and "Secondary" in the router web GUI  'Dual Wan' page. 
 
If there is a way to add something like this to wan-failover that would be great and make the manual changeover process quicker, but the workaround is OK.

**Comment by Ranger802004** [comment]
The GUI configuration you just referred to is the reason why that function doesn't exist within the script.
