### ISSUE TITLE
Domain VPN routing Beta 2.1.0-beta 5 - WAN fwamrk

### ISSUE THREAD

**Issue by dorner365** [Ranger802004/asusmerlin#8]
Hi,

I upgraded to the latest beta (5), reset the configuration and rebooted. Then I reconfigured the configuration items as they previously were and all came back and seems to be working as before. However, the WAN FwMark and Mask still show as before:

ip rule <snip>
0:      from all lookup local
150:    from all fwmark 0x80000000/0xf0000000 lookup main
4000:   from all fwmark 0x7000/0xf000 lookup ovpnc4
7000:   from all fwmark 0xb000/0xf000 lookup wgc2
10000:  from all fwmark 0xe000/0xf000 lookup wgc5

and from the PREROUTING chain <snip>
6     3049  462K MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set DomainVPNRouting-<ipset>-ipv4 dst MARK xset 0x80000000/0xf0000000
7        4   220 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set DomainVPNRouting-<ipset>-ipv4 dst MARK xset 0xb000/0xf000

Any thoughts?

**Comment by Ranger802004** [comment]
Good catch, I see why this is occuring and it was a missed edit, will resolve in next release which hopefully will be 2.1.0 final.

**Comment by dorner365** [comment]
Here's another one - option 11 to edit a policy and enable logging (was originally disabled)

Select the Policy You Want to Edit: cloud
Press any key to continue to edit Policy: cloud
Interfaces:
ovpnc4
ovpnc5
ovpns1
wgc1
wgc2
wgc4
wgc5
wan
Current Interface: wan
Select an Interface for this Policy: wan
Enable verbose logging for this policy? ***Enter Y for Yes or N for No*** y
Enable Private IP Addresses for this policy? ***Enter Y for Yes or N for No*** n
domain_vpn_routing: Edit Policy - Modified cloud in /jffs/configs/domain_vpn_routing/domain_vpn_routing.conf
/jffs/scripts/domain_vpn_routing.sh: line 26: ifnotinuse: parameter not set

...and on the same edit policy item 11 would it be possible to add an option to rename a policy?

**Comment by Ranger802004** [comment]
> Here's another one - option 11 to edit a policy and enable logging (was originally disabled)
> 
> Select the Policy You Want to Edit: cloud Press any key to continue to edit Policy: cloud Interfaces: ovpnc4 ovpnc5 ovpns1 wgc1 wgc2 wgc4 wgc5 wan Current Interface: wan Select an Interface for this Policy: wan Enable verbose logging for this policy? _**Enter Y for Yes or N for No**_ y Enable Private IP Addresses for this policy? _**Enter Y for Yes or N for No**_ n domain_vpn_routing: Edit Policy - Modified cloud in /jffs/configs/domain_vpn_routing/domain_vpn_routing.conf /jffs/scripts/domain_vpn_routing.sh: line 26: ifnotinuse: parameter not set
> 
> ...and on the same edit policy item 11 would it be possible to add an option to rename a policy?

Thank you for this post, I'll fix the issue with the missing parameter in that function.  At this time, changing the name of a policy has too many technical challenges and may be something I work on in a later release.

**Comment by Ranger802004** [comment]
beta6 published to fix this issue.

**Comment by dorner365** [comment]
I upgraded from 2.1 B5 to Beta 6. Then I rebooted the router and it came back as expected. However, the issue with edit policy is still there. Again, please check my earlier feed-back in https://github.com/Ranger802004/asusmerlin/issues/8#issuecomment-1749697707.

The intent of editing the policy is to enable logging (initially it was not logging).. Of interest is the fact that I do not change the interface. That stays the same: wan; I only change the logging option to yes. The error is as above in the mentioned entry

Note, that when I go back to list the policy, logging shows as enabled. But at the end of edit, the script quits abruptly.

**Comment by Ranger802004** [comment]
I found the issue, it was a typo in the command at the bottom of the function looking for the parameter being set to null or not and the way it was typed was trying to read the parameter as if it was already set when it isn't unless you are changing the interface.  It is 100% fixed now, it shouldn't effect functionality other than being a visual bug / issue.

**Comment by Ranger802004** [comment]
v2.1.0 final has been released, thank you for your findings!

**Comment by dorner365** [comment]
I'll close this one since beta is over. Thank you
