### ISSUE TITLE
Domain vpn routing - v2.1.0 - update issue

### ISSUE THREAD

**Issue by dorner365** [Ranger802004/asusmerlin#9]
This is the outcome of an update form 2.1 Beta 6 to v2.1.0 final:

Make a selection:
"6
domain_vpn_routing: ***domain_vpn_routing failed Checksum Check*** Current Checksum: bc018b5aba6c2a4eeaf603d6bb360e4f69a04d407edcf5be3fc938449ab5d44a  Valid Checksum: f1c1e0949fb4442161db13b068c36afd9c995b881c0a4f4282e3da9e873f35da
***Checksum Failed***
Current Checksum: bc018b5aba6c2a4eeaf603d6bb360e4f69a04d407edcf5be3fc938449ab5d44a  Valid Checksum: f1c1e0949fb4442161db13b068c36afd9c995b881c0a4f4282e3da9e873f35da
domain_vpn_routing is up to date. Do you want to reinstall domain_vpn_routing Version: v2.1.0-beta6? ***Enter Y for Yes or N for No***
>"

This happens regardless, whether development mode is enabled or not.

**Comment by Ranger802004** [comment]
That is normal with a beta installed and going to a production release, just let it reinstall.

**Comment by dorner365** [comment]
Well, I let it reinstall and now it shows:

# Domain VPN Routing for ASUS Routers using Merlin Firmware v386.7 or newer
# Author: Ranger802004 - https://github.com/Ranger802004/asusmerlin/
# Date: 10/06/2023
# Version: v2.1.0

So it did take the upgrade to the final version. However, if I select update at this point, that's the outcome:

Make a selection:
6
domain_vpn_routing: ***domain_vpn_routing failed Checksum Check*** Current Checksum: bc018b5aba6c2a4eeaf603d6bb360e4f69a04d407edcf5be3fc938449ab5d44a  Valid Checksum: f1c1e0949fb4442161db13b068c36afd9c995b881c0a4f4282e3da9e873f35da
***Checksum Failed***
Current Checksum: bc018b5aba6c2a4eeaf603d6bb360e4f69a04d407edcf5be3fc938449ab5d44a  Valid Checksum: f1c1e0949fb4442161db13b068c36afd9c995b881c0a4f4282e3da9e873f35da
domain_vpn_routing is up to date. Do you want to reinstall domain_vpn_routing Version: v2.1.0-beta6? ***Enter Y for Yes or N for No***
>

That begs the question which version is now really installed?

**Comment by dorner365** [comment]
Sorry for the formatting - it was just a cut-and-paste from the CLI

**Comment by Ranger802004** [comment]
Reload from your command console, it likely is upgraded but the running version in your session won't change until you reload it, this is a normal limitation of working within a shell. It saves the running version in memory so it will still think it's the old one.

**Comment by dorner365** [comment]
I exited the session and started a new one. It looks alright now:

Make a selection:
6
domain_vpn_routing is up to date. Do you want to reinstall domain_vpn_routing Version: v2.1.0? ***Enter Y for Yes or N for No***

Closing it. Thank you!

**Comment by Ranger802004** [comment]
To give context the reason why the beta gives the checksum error is because the versions are seen the same as prod when the update function compares local to the remote repo one available, because they both are seen as "v2.1.0" it throws a checksum error asking to reinstall, this would also happen if you modify the script file locally and try and update.  When the update completes the loaded version is still loaded as the prior version but the ones executed by cron job will run as the new version so you are effectively updated.
